### ISSUE TITLE
RangeError Exception When MultiPage Wraps Across Pages Sometimes

### ISSUE THREAD

**Issue by scottdewald** [DavBfr/dart_pdf#1028]
**Describe the bug**
First of all, thank you for this library. It has been very helpful for me.

I am using `pdf 3.7.4` for Flutter.

I am using a single `MultiPage` within a `Document` with many `Table`s within the page. The content for the tables is user-generated. For most of the combinations of user content the PDF generation works as expected. However, there are certain edge cases which cause page-wrapping which results in the exception below. I have tried to make sure that no individual widget is larger than a single page as described in the docs.

Here is the exception:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      Table.layout (package:pdf/src/widgets/table.dart:565:26)
#2      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:322:15)
#3      Document.addPage (package:pdf/src/widgets/document.dart:117:10)
#4      Pdfs.createWorkflowSummary (package:my_app/views/pdf/Pdfs.dart:64:9)
<asynchronous suspension>
#5      Pdfs.processExportWorkflowSummaryRequest (package:my_app/views/pdf/Pdfs.dart:41:17)
<asynchronous suspension>
#6      _SummaryPageState._onExportPdfRequested (package:my_app/views/workflow/day0/SummaryPage.dart:580:7)
<asynchronous suspension>
```

**To Reproduce**
Here is the document container for the code. The `body` represents an array of many tables populated with user-generated content.
```dart
static Future<pw.Document> createWorkflowSummary({
    required ReportCompanyInfo companyInfo,
    required List<pw.Widget> body,
  }) async {
    final logoImage = await _loadLogo();
    final formatter = DateFormat.yMd().add_jm();
    final dateTimeText = formatter.format(DateTime.now());
    final pdf = pw.Document();

    pdf.addPage(pw.MultiPage(
      maxPages: 1000,
      pageTheme: pw.PageTheme(
        theme: pw.ThemeData.withFont(
          base: await _loadFontAsset('assets/fonts/OpenSans-Regular.ttf'),
          bold: await _loadFontAsset('assets/fonts/OpenSans-Bold.ttf'),
          italic: await _loadFontAsset('assets/fonts/OpenSans-Italic.ttf'),
        )
      ),
      header: (context) => _createHeader(companyInfo),
      footer: (context) => _createFooter(logoImage, context, dateTimeText),
      build: (pw.Context context) => body
    ));

    return pdf;
  }
```

**Expected behavior**
PDF to be generated without exception.

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 2.10.5 at /Users/scottdewald/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/scottdewald/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone SE (3rd generation) (mobile) • 7F888F57-79AB-4572-8834-C026BE724EED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Desktop (please complete the following information):**
 - [x] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by DavBfr** [comment]
@scottdewald I'll need a self-contained example that reproduces the issue each time, otherwise, there is no way to fix that.

**Comment by DavBfr** [comment]
Could be one of the tests on `index` lines 549 or 581 in `package:pdf/src/widgets/table.dart` which is not accurate.
Can you try to fix it?

**Comment by scottdewald** [comment]
Was able to work around it with this [pull request](https://github.com/DavBfr/dart_pdf/pull/1038).

The issue was the `_heights` list was empty but it was still trying to access it when `heightIndex=0`;
