### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Alvarocda** [DavBfr/dart_pdf#1047]
**Describe the bug**
I'm trying to preview a PDF like the example, but when I try to preview the preview, I get the error message "No such file or directory"

**To Reproduce**
method previewPDF calls generatePDF and with the return of geneatePDF method, i call the screen where i display the preview of PDF
Code snippet to reproduce the behavior:
```dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pdf;
// Class where i create 
pdf.Document generatePdf(){
  pdf.Document doc = pdf.Document();
  doc.addPage(
    pdf.Page(
      pageFormat: PdfPageFormat.a4,
      build: (context) {
        return pdf.Text('Test');
      },
    ),
  );
  return doc;
}

void previewPdf(){
  AssinaturaService assinaturaService = AssinaturaService();
  pw.Document? termo = assinaturaService.generatePdf();
  if (termo != null) {
    await Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => TestScreen(doc: termo),
      ),
    );
  }
}



// My screen where i preview the PDF

import 'package:flutter/material.dart';
import 'package:pdf/src/pdf/page_format.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
class TestScreen extends StatelessWidget {
  final pw.Document doc;

  const TestScreen({required this.doc, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: Container(
        child: PdfPreview(
          build: (PdfPageFormat format) => doc.save(),
          initialPageFormat: PdfPageFormat.a4,
          loadingWidget: const CustomLoading(
            mensagem: Text('Carregando visualização'),
          ),
          canChangeOrientation: false,
          dynamicLayout: false,
          canChangePageFormat: false,
          canDebug: false,
          pdfFileName: 'Termo de assentimento',
          useActions: false,
        ),
      ),
    );
  }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12532704/168887188-572a984a-7d6a-4c55-a9fc-7039ce8124ca.png)

**Flutter Doctor**

```
 flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on Linux Mint 20.2 5.13.0-41-generic, locale pt_BR.UTF-8)
    • Flutter version 3.0.0 at /mnt/Arquivos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /mnt/Arquivos/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /mnt/Arquivos/Android/Sdk
    • Java binary at: /mnt/Arquivos/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /mnt/Arquivos/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /mnt/Arquivos/idea-IC-212.5457.46
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Linux (desktop)                  • linux         • linux-x64      • Linux Mint 20.2 5.13.0-41-generic
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [X] Android
 - [ ] Browser
 - [ ] Windows
 - [ ] Linux

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 11

**Additional context**
Printing, saving or sharing the PDF works pefectly, only previwing is not working

**Comment by Alvarocda** [comment]
```
I/flutter (14138): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (14138): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (14138): Helvetica-Oblique has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfPageList
I/flutter (14138): Creation time: 0.003366 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfCatalog
I/flutter (14138): Creation time: 0.002066 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfInfo
I/flutter (14138): Creation time: 0.001094 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfPage
I/flutter (14138): Creation time: 0.003174 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfPage
I/flutter (14138): Creation time: 0.000219 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfObjectStream
I/flutter (14138): Creation time: 0.004124 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfType1Font
I/flutter (14138): Creation time: 0.000587 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutline
I/flutter (14138): Creation time: 0.001865 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutline
I/flutter (14138): Creation time: 0.000171 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutline
I/flutter (14138): Creation time: 0.000106 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutline
I/flutter (14138): Creation time: 0.000063 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfType1Font
I/flutter (14138): Creation time: 0.000054 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfTtfFont
I/flutter (14138): Creation time: 0.015556 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfObjectStream
I/flutter (14138): Creation time: 0.000611 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfUnicodeCmap
I/flutter (14138): Creation time: 0.001175 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfFontDescriptor
I/flutter (14138): Creation time: 0.002598 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfArrayObject
I/flutter (14138): Creation time: 0.00044 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutline
I/flutter (14138): Creation time: 0.000081 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfTtfFont
I/flutter (14138): Creation time: 0.003923 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfObjectStream
I/flutter (14138): Creation time: 0.001367 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfUnicodeCmap
I/flutter (14138): Creation time: 0.000512 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfFontDescriptor
I/flutter (14138): Creation time: 0.000214 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfArrayObject
I/flutter (14138): Creation time: 0.000354 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): Jpeg Image 2086x1939
I/flutter (14138): Creation time: 0.002338 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfNames
I/flutter (14138): Creation time: 0.001699 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): RAW RGBA Image 400x439
I/flutter (14138): Creation time: 0.02244 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): Image alpha channel 400x439
I/flutter (14138): Creation time: 0.005464 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfObjectStream
I/flutter (14138): Creation time: 0.000893 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfType1Font
I/flutter (14138): Creation time: 0.000124 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): RAW RGBA Image 333x112
I/flutter (14138): Creation time: 0.005037 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): Image alpha channel 333x112
I/flutter (14138): Creation time: 0.001455 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): RAW RGBA Image 168x136
I/flutter (14138): Creation time: 0.004421 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfImage
I/flutter (14138): Orientation: PdfImageOrientation.topLeft
I/flutter (14138): Image alpha channel 168x136
I/flutter (14138): Creation time: 0.001506 seconds
I/flutter (14138): 
I/flutter (14138): ------------------------------------------------------------------------------
I/flutter (14138): PdfOutput
I/flutter (14138): Verbose dart_pdf
I/flutter (14138): Producer https://github.com/DavBfr/dart_pdf
I/flutter (14138): Creation date: 2022-05-17 14:55:34.879693
I/flutter (14138): Creation time: 0.116149 seconds
I/flutter (14138): File size: 654267 bytes
I/flutter (14138): Pages: 2
I/flutter (14138): Objects: 34
W/System.err(14138): java.io.IOException: No such file or directory
W/System.err(14138): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err(14138): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err(14138): 	at java.io.File.createTempFile(File.java:2018)
W/System.err(14138): 	at net.nfet.flutter.printing.PrintingJob$3.run(PrintingJob.java:448)
W/System.err(14138): 	at java.lang.Thread.run(Thread.java:923)
```
