### ISSUE TITLE
pdf image is not loading with printing package. It is showing error

### ISSUE THREAD

**Issue by ankit007im** [DavBfr/dart_pdf#105]
When I use printing.dart with pdf package to load image from assets it is showing error
Error:
```
E/flutter (24346): [ERROR:flutter/lib/ui/painting/codec.cc(207)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter (24346): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (24346): The following assertion was thrown when reporting an error to an image listener:
I/flutter (24346): image failed to load
I/flutter (24346): 'package:printing/src/asset_utils.dart':
I/flutter (24346): Failed assertion: line 59 pos 14: 'false'
I/flutter (24346):
I/flutter (24346): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24346): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24346): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24346):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24346):
I/flutter (24346): When the exception was thrown, this was the stack:
I/flutter (24346): #2      pdfImageFromImageProvider.<anonymous closure> (package:printing/src/asset_utils.dart:59:14)
I/flutter (24346): #3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:474:24)
I/flutter (24346): #4      new MultiFrameImageStreamCompleter.<anonymous closure> (package:flutter/src/painting/image_stream.dart:590:7)
I/flutter (24346): #14     AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart)
I/flutter (24346): <asynchronous suspension>
I/flutter (24346): #15     AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
I/flutter (24346): #16     ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:48)
I/flutter (24346): #17     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (24346): #18     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:25)
I/flutter (24346): (elided 24 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter (24346): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (24346): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:pdf/widgets/image.dart': Failed assertion: line 21 pos 16: 'image != null': is not true.
E/flutter (24346): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (24346): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24346): #2      new Image (package:pdf/widgets/image.dart:21:16)
E/flutter (24346): #3      pdf.<anonymous closure> (package:sna_sales/pdf.dart:53:31)
E/flutter (24346): #4      Page.postProcess (package:pdf/widgets/document.dart:169:28)
E/flutter (24346): #5      Document.save (package:pdf/widgets/document.dart:67:12)
E/flutter (24346): #6      pdf (package:sna_sales/pdf.dart:395:31)
E/flutter (24346): <asynchronous suspension>
E/flutter (24346): #7      _HomePageState.createFileOfPdfUrl (package:sna_sales/pages/home_page.dart:76:15)
E/flutter (24346): <asynchronous suspension>
E/flutter (24346): #8      _HomePageState.initState (package:sna_sales/pages/home_page.dart:55:5)
E/flutter (24346): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
E/flutter (24346): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter (24346): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (24346): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (24346): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (24346): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (24346): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
E/flutter (24346): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
E/flutter (24346): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
E/flutter (24346): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
E/flutter (24346): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
E/flutter (24346): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
E/flutter (24346): #21     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (24346): #22     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24346): #23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24346): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24346): #25     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24346): #26     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24346): #27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (24346): #28     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (24346): #29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (24346): #30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (24346): #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
My Code:
```
final Document pdf = Document(deflate: zlib.encode);
PdfImage logoImage = await pdfImageFromImageProvider(
    pdf: pdf.document,
    image: AssetImage('assets/logo.png')
  );
 pdf.addPage(
    Page(
build: (Context context) {
          return ListView(
            children: <Widget>[
                      Container(
                      margin: EdgeInsets.only(top:30),
                        child:Image(logoImage)
                 ),
]
)

I am expecting to show image in the pdf when I view it by pdf viewer

 - [ ] iOS
 - [ ✔] Android
 - [ ] Browser

**Comment by DavBfr** [comment]
This error is reported by the flutter engine. Can you make sure this image is a valid png?

**Comment by ankit007im** [comment]
Yes, It is the problem with png but when I used it in my other file it runs smoothly.
 Can you tell how can I adjust the image size?
Thanks for helping.

**Comment by DavBfr** [comment]
Try PngCrush: https://pngcrush.com/

**Comment by ankit007im** [comment]
sorry for not being clear to you I meant image height and width😊

**Comment by DavBfr** [comment]
Use your favorite image editor, like https://www.gimp.org/

**Comment by ankit007im** [comment]
It is not possible to use height: 20, width: 20 inside the widget

**Comment by DavBfr** [comment]
You can set a width and height to the container, that will do.

**Comment by ankit007im** [comment]
ok got it thanks for help😊😊
