### ISSUE TITLE
This is not a simple glyph

### ISSUE THREAD

**Issue by HuseynHuseyni** [DavBfr/dart_pdf#1053]
Hi, I had no problem using English letters when using the package in the latest version 3.8.0.
But in some cases when I used Arabic letters, I encountered the following error:

- **error = This is not a simple glyph :** 

```
E/flutter ( 3912): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:pdf/src/pdf/font/ttf_writer.dart': Failed assertion: line 97 pos 18: 'glyph.compounds.isEmpty': This is not a simple glyph
E/flutter ( 3912): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 3912): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 3912): #2      TtfWriter.withChars.<anonymous closure> (package:pdf/src/pdf/font/ttf_writer.dart:97:18)
E/flutter ( 3912): #3      ListMixin.firstWhere (dart:collection/list.dart:166:38)
E/flutter ( 3912): #4      TtfWriter.withChars (package:pdf/src/pdf/font/ttf_writer.dart:93:32)
E/flutter ( 3912): #5      PdfTtfFont._buildType0 (package:pdf/src/pdf/obj/ttffont.dart:110:28)
E/flutter ( 3912): #6      PdfTtfFont.prepare (package:pdf/src/pdf/obj/ttffont.dart:151:7)
E/flutter ( 3912): #7      PdfObject.write (package:pdf/src/pdf/obj/object.dart:51:5)
E/flutter ( 3912): #8      PdfOutput.write (package:pdf/src/pdf/output.dart:105:8)
E/flutter ( 3912): #9      SetMixin.forEach (dart:collection/set.dart:142:30)
E/flutter ( 3912): #10     PdfDocument._write (package:pdf/src/pdf/document.dart:216:13)
E/flutter ( 3912): #11     PdfDocument.save (package:pdf/src/pdf/document.dart:228:11)
E/flutter ( 3912): #12     Document.save (package:pdf/src/widgets/document.dart:135:27)
E/flutter ( 3912): #13     PdfApi.saveDocument (package:generate_pdf_image_example/api/pdf_api.dart:187:29)
E/flutter ( 3912): #14     PdfApi.generateImage (package:generate_pdf_image_example/api/pdf_api.dart:180:12)
E/flutter ( 3912): <asynchronous suspension>
E/flutter ( 3912): #15     _PdfPageState.build.<anonymous closure> (package:generate_pdf_image_example/page/pdf_page.dart:38:37)
E/flutter ( 3912): <asynchronous suspension>
```

After many tests, I realized that the modes that cause the error are limited to the modes that use this letters :

  **`\u0628 \u062C ("ب" or  "ج" (in Arabic)).`**

- **Sample code without error :**

```dart
  static Future<File> generateImage() async {
    var data = await rootBundle.load(
        "assets/fonts/IranSansXPro/Farsi numerals/IRANSansXFaNum-DemiBold.ttf");

    final ttf = Font.ttf(data);

    final pdf = Document();

    final imageSvg = await rootBundle.loadString('assets/fruit.svg');
    final imageJpg =
        (await rootBundle.load('assets/invoice.jpg')).buffer.asUint8List();
    const double fieldsFontSize = 14;

    final pageTheme = PageTheme(
      margin: const EdgeInsets.all(22),
      theme: ThemeData.withFont(
        base: ttf,
      ),
      textDirection: TextDirection.rtl,
      pageFormat: PdfPageFormat.a4,
      buildBackground: (context) {
        if (context.pageNumber == 1) {
          return FullPage(
            ignoreMargins: true,
            child: Image(MemoryImage(imageJpg), fit: BoxFit.cover),
          );
        } else {
          return Container();
        }
      },
    );

    pdf.addPage(
      Page(
        pageTheme: pageTheme,
        build: (context) {
          return Text(
            "اپتثچحخدذرزژسشصضطظعغفقکگلمنوهی",
            //all letters except "ب" and "ج".
            style: const TextStyle(
              fontSize: fieldsFontSize,
            ),
          );
        },
      ),
    );

    return saveDocument(name: 'my_example.pdf', pdf: pdf);
  }
```

- **Sample code that causes the error :**

```dart
  static Future<File> generateImage() async {
    var data = await rootBundle.load(
        "assets/fonts/IranSansXPro/Farsi numerals/IRANSansXFaNum-DemiBold.ttf");

    final ttf = Font.ttf(data);

    final pdf = Document();

    final imageSvg = await rootBundle.loadString('assets/fruit.svg');
    final imageJpg =
        (await rootBundle.load('assets/invoice.jpg')).buffer.asUint8List();
    const double fieldsFontSize = 14;

    final pageTheme = PageTheme(
      margin: const EdgeInsets.all(22),
      theme: ThemeData.withFont(
        base: ttf,
      ),
      textDirection: TextDirection.rtl,
      pageFormat: PdfPageFormat.a4,
      buildBackground: (context) {
        if (context.pageNumber == 1) {
          return FullPage(
            ignoreMargins: true,
            child: Image(MemoryImage(imageJpg), fit: BoxFit.cover),
          );
        } else {
          return Container();
        }
      },
    );

    pdf.addPage(
      Page(
        pageTheme: pageTheme,
        build: (context) {
          return Text(
            "ب ج",
            //only the previous text has been replaced with "ب" or "ج"
            style: const TextStyle(
              fontSize: fieldsFontSize,
            ),
          );
        },
      ),
    );

    return saveDocument(name: 'my_example.pdf', pdf: pdf);
  }
```

Please help me, thank you.

**Comment by HuseynHuseyni** [comment]
Apparently, the problem was with the font I was using, which, contrary to my belief, was also a monetary and expensive font (IranSansXPro) and I was sure about it, but by changing the font, everything was fine.

Thank you
