### ISSUE TITLE
Error Printing.listPrinters() in web

### ISSUE THREAD

**Issue by samo92** [DavBfr/dart_pdf#1064]
In web when i use Printing.listPrinters() i got this error

Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:62991/dart_sdk.js:5063:11)
at printing_web.PrintingPlugin.new.listPrinters (http://localhost:62991/packages/printing/printing_web.dart.lib.js:250:17)
at Printing.listPrinters (http://localhost:62991/packages/printing/src/printing.dart.lib.js:109:51)

There is a way to fix in my app?

**Comment by samo92** [comment]
Sorry, this is my code:

```
class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: ElevatedButton(
        onPressed: () async {
          Printing.directPrintPdf(
            printer: (await Printing.listPrinters()).first,
            onLayout: (format) => _buildSinglePdf(test()),
          );
        },
        child: const Text("Direct Print"),
      )),
      // PdfPreview(
      //   build: (format) => _buildSinglePdf(test()),
      // ),
    );
  }
}

Future<Uint8List> _buildSinglePdf(pw.Widget body) async {
  final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
  final font1 = await PdfGoogleFonts.nunitoRegular();
  final font2 = await PdfGoogleFonts.nunitoBold();
  final _customFormat = PdfPageFormat(204, 2000, marginAll: 0.toDouble());

  pdf.addPage(
    pw.Page(
      pageTheme: pw.PageTheme(
        theme: pw.ThemeData.withFont(base: font1, bold: font2),
        pageFormat: _customFormat,
        orientation: pw.PageOrientation.portrait,
      ),
      build: (context) => body,
    ),
  );

  return pdf.save();
}

pw.Widget test() {
  const maxRows = 50;
  const maxCharLength = 100;

  return pw.Column(
    children: [
      pw.Text('Test'),
      pw.Text('-' * maxCharLength, maxLines: 1),
      pw.Text('*' * maxCharLength, maxLines: 1),
      for (var i = 0; i < maxRows; i++)
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [pw.Text('Fila $i'), pw.Text('\$${maxRows - i}.0000')],
        ),
      pw.Text('@' * maxCharLength, maxLines: 1),
    ],
  );
}
```

**Comment by DavBfr** [comment]
Not possible. There is no web API to do that.

**Comment by techttiru** [comment]
> Sorry, this is my code:
> 
> Note: When test my code i have 2 printers available (turn on and coneccted)
> 
> ```
> class Home extends StatelessWidget {
>   const Home({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Center(
>           child: ElevatedButton(
>         onPressed: () async {
>           Printing.directPrintPdf(
>             printer: (await Printing.listPrinters()).first,
>             onLayout: (format) => _buildSinglePdf(test()),
>           );
>         },
>         child: const Text("Direct Print"),
>       )),
>       // PdfPreview(
>       //   build: (format) => _buildSinglePdf(test()),
>       // ),
>     );
>   }
> }
> 
> Future<Uint8List> _buildSinglePdf(pw.Widget body) async {
>   final pdf = pw.Document(version: PdfVersion.pdf_1_5, compress: true);
>   final font1 = await PdfGoogleFonts.nunitoRegular();
>   final font2 = await PdfGoogleFonts.nunitoBold();
>   final _customFormat = PdfPageFormat(204, 2000, marginAll: 0.toDouble());
> 
>   pdf.addPage(
>     pw.Page(
>       pageTheme: pw.PageTheme(
>         theme: pw.ThemeData.withFont(base: font1, bold: font2),
>         pageFormat: _customFormat,
>         orientation: pw.PageOrientation.portrait,
>       ),
>       build: (context) => body,
>     ),
>   );
> 
>   return pdf.save();
> }
> 
> pw.Widget test() {
>   const maxRows = 50;
>   const maxCharLength = 100;
> 
>   return pw.Column(
>     children: [
>       pw.Text('Test'),
>       pw.Text('-' * maxCharLength, maxLines: 1),
>       pw.Text('*' * maxCharLength, maxLines: 1),
>       for (var i = 0; i < maxRows; i++)
>         pw.Row(
>           mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
>           children: [pw.Text('Fila $i'), pw.Text('\$${maxRows - i}.0000')],
>         ),
>       pw.Text('@' * maxCharLength, maxLines: 1),
>     ],
>   );
> }
> ```

@samo92 - Hi, were you able to find the work around or any other alternate option for this issue? i am also trying to connect the USB device printer in widows machine from flutter web. is that possible?

@DavBfr  - Hi, Any comment on this? Appreciate the response.
