### ISSUE TITLE
Error with version 3.8.1

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#1066]
```
======== Exception caught by printing ==============================================================
The following RangeError was thrown while rastering a PDF:
RangeError (index): Invalid value: Valid value range is empty: 1

When the exception was thrown, this was the stack: 
#0      List._setIndexed (dart:core-patch/growable_array.dart:273:49)
#1      List.[]= (dart:core-patch/growable_array.dart:268:5)
#2      PdfPreviewRaster._raster (package:printing/src/preview/raster.dart:177:16)
<asynchronous suspension>
PageFormat: "PdfPageFormat 595.275590551181x841.8897637795275 margins:56.69291338582677, 56.69291338582677, 56.69291338582677, 56.69291338582677"
====================================================================================================
E/flutter (26973): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: setState() called after dispose(): PdfPreviewCustomState#285f8(lifecycle state: defunct, not mounted)
E/flutter (26973): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (26973): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (26973): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (26973): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1073:9)
E/flutter (26973): #1      State.setState (package:flutter/src/widgets/framework.dart:1108:6)
E/flutter (26973): #2      PdfPreviewRaster._raster (package:printing/src/preview/raster.dart:213:7)
E/flutter (26973): <asynchronous suspension>
E/flutter (26973): 
```

**Comment by deepak786** [comment]
It seems that this commit https://github.com/DavBfr/dart_pdf/commit/21be6b5644e068e8e1a9f241cc5acc03833df38f resolves the issue.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=LLBoRBAQIw0
