### ISSUE TITLE
How do I display pdf from a pdf file？

### ISSUE THREAD

**Issue by cyz1901** [DavBfr/dart_pdf#1166]
Hello team, I want to display pdf from a pdf file.
I think the file should be converted into bit data and then into MemoryImage.
So I wirte code like
```
    final image = pw.MemoryImage(
      (await rootBundle.load('assets/text.pdf')).buffer.asUint8List(),
    );
```

But It seems that `pdfDecoder` does not exist in `findDecoderForData`
so i get error
```
The following _Exception was thrown while generating a PDF:
Exception: Unable to guess the image type 5263 bytes
When the exception was thrown, this was the stack: 
#0      new MemoryImage (package:pdf/src/widgets/image_provider.dart:103:7)
#1      HomePage.generateCalendar (package:pdf_demo/pages/home/home_view.dart:81:22)
<asynchronous suspension>
#2      PdfPreviewRaster._raster (package:printing/src/preview/raster.dart:124:14)
<asynchronous suspension>
PageFormat: "PdfPageFormat 612.0x792.0 margins:72.0, 72.0, 72.0, 72.0"
```
Could anyone give me some advice？:eyes:

**Comment by PrateekJain1993** [comment]
Did u find the best way to view pdf then? Can u please suggest a good way to load pdf from a network request?
