### ISSUE TITLE
packages__pdf__src__pdf__obj__signature error flutter web

### ISSUE THREAD

**Issue by TaifRaoof** [DavBfr/dart_pdf#1313]
Hi
i have updated the library to last version and i have last version of dart so when i run my flutter web project the error is appear in console and the project not load and working.
signature.pdf error.

**Comment by insinfo** [comment]
I'm also having this problem with an AngularDart web project in Dart 2.18.
the problem occurs only with 3.10.0, 3.9.0 is ok

**Comment by Theinksquid1927** [comment]
I am also having a problem import the package since last update. Using package in Flutterflow custom action. Project will not load. Getting 2 error messages:

"Uncaught SyntaxError: Unexpected token 'null' (at signature.dart.js:41:9)"

"Uncaught TypeError: Cannot read properties of undefined (reading 'src__pdf__graphics')
    at load__packages__pdf__src__widgets__table_dart (table.dart.js:20:67)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)"

**Comment by DavBfr** [comment]
Fixed in pdf version 3.10.1
