### ISSUE TITLE
I encountered an error while deploying Flutter using GitLab CI.

### ISSUE THREAD

**Issue by RonanDex** [DavBfr/dart_pdf#1388]
**Describe the bug**
Compiling lib/main.dart for the Web...                          
#15 32.06 Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dev/pdf_widget_wrapper-1.0.0/lib/src/widget_wrapper.dart:180:7:

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// "Compilation error"
flutter build web --web-renderer html --release
```

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [*] Linux

**Smartphone (please complete the following information):**
 - gitlab-ci docker dart:2.19.4 dind
 - 
**Additional context**

#15 0.987 Downloading Web SDK...                                              3.7s
#15 6.446 Resolving dependencies...
#15 7.813 > async 2.11.0 (was 2.10.0)
#15 7.814 > characters 1.3.0 (was 1.2.1)
#15 7.814 > collection 1.17.1 (was 1.17.0) (1.17.2 available)
#15 7.814 > js 0.6.7 (was 0.6.5)
#15 7.815   lints 2.0.1 (2.1.0 available)
#15 7.815 > matcher 0.12.15 (was 0.12.13) (0.12.16 available)
#15 7.815   material_color_utilities 0.2.0 (0.5.0 available)
#15 7.816 > meta 1.9.1 (was 1.8.0)
#15 7.816 > path 1.8.3 (was 1.8.2)
#15 7.816   pdf 3.10.1 (3.10.3 available)
#15 7.817   pdf_widget_wrapper 1.0.0 (1.0.1 available)
#15 7.817   petitparser 5.1.0 (5.4.0 available)
#15 7.817   screenshot 1.3.0 (2.1.0 available)
#15 7.818   source_span 1.9.1 (1.10.0 available)
#15 7.818 > test_api 0.5.1 (was 0.4.16) (0.6.0 available)
#15 7.818   win32 4.1.4 (5.0.2 available)
#15 7.818   xml 6.2.2 (6.3.0 available)
#15 7.820 Changed 8 dependencies!
#15 8.346 
#15 8.387 Compiling lib/main.dart for the Web...                          
#15 32.06 Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dev/pdf_widget_wrapper-1.0.0/lib/src/widget_wrapper.dart:180:7:
#15 32.06 Error: No named parameter with the name 'window'.
#15 32.06       window: view,
#15 32.06       ^^^^^^
#15 32.06 /flutter/packages/flutter/lib/src/rendering/view.dart:68:3:
#15 32.06 Info: Found this candidate, but the arguments don't match.
#15 32.06   RenderView({
#15 32.06   ^^^^^^^^^^
#15 32.06 Error: Compilation failed.
#15 32.06

**Comment by RonanDex** [comment]
By the way, just to clarify, I'm using the same command `flutter build web --web-renderer html —release` for compilation on both Mac and Windows, and I don't receive any error messages.

**Comment by RonanDex** [comment]
ci file

```
FROM dart:2.19.4-sdk AS builder

RUN apt-get update && apt-get install -y git unzip

RUN git clone https://github.com/flutter/flutter.git -b stable --depth 1 /flutter

ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:$PATH"

WORKDIR /app
COPY pubspec.* ./
RUN flutter pub get

COPY . .
RUN flutter build web --web-renderer html --release



FROM nginx:alpine
COPY --from=builder /app/build/web /usr/share/nginx/html
```
