### ISSUE TITLE
Error about too many pages created in pdf (more than 20 pages)

### ISSUE THREAD

**Issue by Mar-debug** [DavBfr/dart_pdf#1458]
Using your package for the pdf generating and saving, i have network images in the PDF, which i used your code to insert them into the pdf along with some text, but i get the following error :

[log] ERROR: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. See https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html
[log] ERROR: #0      MultiPage.generate.<anonymous closure> (package:pdf/src/widgets/multi_page.dart:251:11)
#1      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:255:8)
#2      Document.addPage (package:pdf/src/widgets/document.dart:117:10)

I checked the documentation and there is no limits to the pages in the created pdf, anything you can give to help me would be great

**Comment by Mar-debug** [comment]
changed the max pages from 20 to 500, but i still get the error about created more than 500 pages

**Comment by Mar-debug** [comment]
I only needed to add height and width to my image for it to render properly
