### ISSUE TITLE
true type font handling error

### ISSUE THREAD

**Issue by hendrik-brower** [DavBfr/dart_pdf#1549]
**Describe the bug**
When generating the pdf output, there is an error in the ttf glyph handling.

The result is a crash; however, if one prints more text in the pdf, the crash is
avoided; however, data corruption occurs and rendered text is messed up with
the visible effect being that space characters are written as some random glyph.

I think this is a relatively serious error.  In general use, I am not seeing crashes;
however, I believe a corrupted pdf is generated fairly often (>25% of the time).  The
crash would be less serious in a way because one would know they have an error
where as in this case, you just get a bad pdf.

**To Reproduce**
I created a project to catch the issue.  It can be found at:
https://github.com/hendrik-brower/pdf_issue/blob/main/bin/pdf_issue.dart

In that project there is a "out" directory with generated pdf files.  The crashes
do not generate a pdf, however, you can see iterations (90-104) before and after the
crashing iterations. In all iterations after the crash, the pdf is corrupted.

Code snippet to reproduce the behavior:
https://github.com/hendrik-brower/pdf_issue/blob/main/bin/pdf_issue.dart
https://github.com/hendrik-brower/pdf_issue/blob/main/bin/output.txt

The last good pdf file:
https://github.com/hendrik-brower/pdf_issue/blob/main/out/ex.096.pdf

The subsequent bad pdf files:
https://github.com/hendrik-brower/pdf_issue/blob/main/out/ex.099.pdf
https://github.com/hendrik-brower/pdf_issue/blob/main/out/ex.100.pdf
as well as 101, 102, 103, 104

When the pdf processing first fails, the output for that run is:
```
test run 8
charCount=97
attempting to generate a pdf with the text:
abcd efgh ijkl mnop
f#sju D -pF <y9oP  2[wZ X{u~A =-gsG 
`u}KU k9g+t Ua)u/ #ia*Q |X:8H "(vV` 
2tA2? x<&k\ [E>8_ 8b,w? C

failed to process data
error: Bad state: No element
stack: #0      Iterable.first (dart:core/iterable.dart:643:7)
#1      TtfWriter.withChars (package:pdf/src/pdf/font/ttf_writer.dart:111:67)
#2      PdfTtfFont._buildType0 (package:pdf/src/pdf/obj/ttffont.dart:114:28)
#3      PdfTtfFont.prepare (package:pdf/src/pdf/obj/ttffont.dart:155:7)
#4      PdfDocument._write (package:pdf/src/pdf/document.dart:225:10)
#5      PdfDocument.save (package:pdf/src/pdf/document.dart:258:11)
#6      main (file:///home/hbrower/github/dart_pdf/pdf/example/main2.dart:64:17)
<asynchronous suspension>
```

**Comment by hendrik-brower** [comment]
I have narrowed this down, though don't completely understand the code base, so I'm not quite sure how to fix this.  The fonts where I see this error are parsed via:
  void _parseCMapFormat4(int basePosition); in ttf_parser.dart
In the two that I was tinkering with, the space (ascii 32), has an index other than 32.
For Sriracha, its 2.  For Tinos, its 3.

However the logic in ttf_writer.dart for the function withChars has a hard coded index:

      if (char == 32) {
        final glyph = TtfGlyphInfo(32, Uint8List(0), const <int>[]);
        glyphsMap[glyph.index] = glyph;
        charMap[char] = glyph.index;
        continue;
      }


The problem is corrected if I use: TtfGlyphInfo(2,...) or TtfGlyphInfo(3,...) for the Sriracha and Tinos fonts respectively.

I am not sure if this is true for every font type, but would the correct fix be:
        final glyph = TtfGlyphInfo(ttf..charToGlyphIndexMap[char]!, Uint8List(0), const <int>[]);
