### ISSUE TITLE
Unhandled Exception: Instance of 'TooManyPagesException' #0      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:251:9)

### ISSUE THREAD

**Issue by naseerx** [DavBfr/dart_pdf#1579]
I was facing this issue [issue](https://github.com/DavBfr/dart_pdf/issues/114) and then i use the Wrap widget. Now the error is

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'TooManyPagesException'
#0      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:251:9)
#1      Document.addPage (package:pdf/src/widgets/document.dart:117:10)
#2      _QuillPageState.generatePdf (package:daiaryapp/pages/addDairyPage/quill_page.dart:76:9)
<asynchronous suspension>
#3      _QuillPageState.build.<anonymous closure>.<anonymous closure> (package:daiaryapp/pages/addDairyPage/quill_page.dart:320:48)
<asynchronous suspension>
```

This is my Code :

```
   pdf.addPage(pw.MultiPage(
      build: (pw.Context context) {
        final content = <pw.Widget>[];

        // Add a title to the PDF
        content.add(
          pw.Center(
            child: pw.Text(
              post.dairyName.toString(), // Replace with your desired title
              style: customTitle,
            ),
          ),
        );

        int itemsPerPage = 8;

        for (var i = 0; i < deltaData['ops'].length; i++) {
          final op = deltaData['ops'][i];

          if (op.containsKey('insert')) {
            if (op['insert'] is String) {
              final lines = (op['insert'] as String).split('-');

              for (var line in lines) {
                final textWidget = pw.Padding(
                  padding: pw.EdgeInsets.all(1.0),
                  child: pw.Text(
                    line.trim(), // Trim to remove extra spaces
                    style: customTextStyle, // Apply custom text style here
                  ),
                );

                content.add(textWidget);
              }
            } else if (op['insert'] is Map &&
                op['insert'].containsKey('image')) {
              final imageData = op['insert']['image'].split(',')[1];
              final Uint8List decodedImage = base64Decode(imageData);

              final imageWidget = pw.Padding(
                padding: pw.EdgeInsets.all(1.0),
                child: pw.Image(
                  pw.MemoryImage(
                    decodedImage,
                  ),
                  fit: pw.BoxFit.cover,
                  height: 245.0,
                ),
              );

              content.add(imageWidget);
            }
          }

          if (i > 0 && (i + 1) % itemsPerPage == 0) {
            content.add(pw.Container(width: 1.0, height: 1.0));
          }
        }

        // return content;
        return [
          pw.Wrap(
            children: content,
          ),
        ];
      },
    ));
```

**Comment by Allenxuxu** [comment]
I have the same issue

**Comment by naseerx** [comment]
> I have the same issue

Lemme know when you get any help, i am still stuck

**Comment by KinsleySen** [comment]
apparently, you need to adjust the content to fit in page 
like the library said https://pub.dev/documentation/pdf/latest/widgets/MultiPage-class.html

if you have a dynamic detail just break it in table or column, and you must try to print / preview to know how many detail that you can fit inside one table then break it to multiple table

**Comment by PlaudAI** [comment]
You can try it. The font size should not exceed 20

**Comment by MrLiuYS** [comment]
You can try it, the font should not be larger than 20

**Comment by aman246149** [comment]
I found a workaround for my case.
Instead of adding multiPage I just add a Single Page and give it max length of content and width of the device and this works for me.
Here is a little Sniipet For That..

`  pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat(
            MediaQuery.of(context).size.width + 100, double.infinity,
            marginAll: 25),
        build: (context) => pw.Column`

**Comment by DhavalRKansara** [comment]
@DavBfr  I am also having the same issues, do we have any plan to fix this in nearby window?

**Comment by johnpsc** [comment]
in my case, i resolved using map instead of using ListView

SizedBox(
          width: width,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              if (data.isNotEmpty) ...[
                ...data.map((e) {
                  return YOURWIDGET(),
                }),
              ],
            
            ],
          ),
        ),

**Comment by mark-brin** [comment]
@johnpsc  even with map if you provide large data/text to single widget (wch overflows page), it will throw the same error then

**Comment by mark-brin** [comment]
> I found a workaround for my case. Instead of adding multiPage I just add a Single Page and give it max length of content and width of the device and this works for me. Here is a little Sniipet For That..
> 
> ` pdf.addPage( pw.Page( pageFormat: PdfPageFormat( MediaQuery.of(context).size.width + 100, double.infinity, marginAll: 25), build: (context) => pw.Column`

@aman246149 its working! but its resizing the first page according to data length passed, this is impacting when trying to print in A4 or some specific page size.
