### ISSUE TITLE
iOS18 Error: `NSInternalInconsistencyException` View was already initialized

### ISSUE THREAD

**Issue by charlieforward9** [DavBfr/dart_pdf#1760]
**Describe the bug**
This is related to upgrading my phone to iOS18. Running iOS17.5 on an iPhone14 emulator renders the PDF correctly.

**To Reproduce**
Try to render a PDF on iOS18

**Expected behavior**

Support for iOS18

**Screenshots**
```shell
*** Assertion failure in -[FLTPDFView _populateInitialTraitCollection:], UIView.m:4639
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'View was already initialized: <FLTPDFView: 0x135d62200; frame = (0 0; 0 0); layer = <CALayer: 0x302fffb60>>'
*** First throw call stack:
(0x1a0be908c 0x19deeb2e4 0x19ffba15c 0x1a33570f8 0x1a3355d68 0x1a3357b64 0x102b113ec 0x102b10e3c 0x102b10cf8 0x10b520c7c 0x10badb43c 0x10b568788 0x100eb8a30 0x100eba71c 0x100ecade8 0x100eca9a4 0x1a0bbbf64 0x1a0bb9188 0x1a0bb85b8 0x1ec64e1c4 0x1a370e5f0 0x1a37bd10c 0x1a3ae9e50 0x1021c49cc 0x1021c4944 0x1021c4a48 0x1c638bd34)
libc++abi: terminating due to uncaught exception of type NSException
```

Using breakpoints and a lot of `Step Into`'s, I was able to generate this log:
```
Concurrent modification during iteration: _Set len:11.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:714:7)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:450:22)
#2      PdfDocument._write (package:pdf/src/pdf/document.dart:224:30)
document.dart:224
#3      PdfDocument.save.<anonymous closure> (package:pdf/src/pdf/document.dart:259:13)
document.dart:259
```

**Flutter Doctor**

```
[✓] Flutter (Channel master, 3.23.0-13.0.pre.100, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] VS Code (version 1.94.0)
[✓] Connected device (4 available)
[✓] Network resources
# Unnecessary Android setups omitted
```

**Desktop (please complete the following information):**
 - [X] iOS

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15]
 - OS: [e.g. iOS 18.0 Developer Beta & iOS 18.0.1 (22A3370)]

**Comment by eldarkk** [comment]
any fix about this

**Comment by charlieforward9** [comment]
I just went through and bumped all my dependencies and now I'm not getting this problem anymore. 

I believe it's actually a problem with `flutter_pdfview` when I bumped it from `^1.1.2` to `^1.1.3`, it works.

If you confirm this, I will close the issue.
