### ISSUE TITLE
Caused by java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by mjafartp** [DavBfr/dart_pdf#191]
**Describe the bug**
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
       at net.nfet.flutter.printing.PrintingPlugin.registerWith(:29)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:103)
       at com.lithoserp.fieldsales.Application.registerWith(:5)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(:71)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(:41)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(:41)
       at android.app.job.JobService$1.onStartJob(JobService.java:62)
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Flutter Doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.5 at /home/lithos/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/lithos/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/lithos/Android/Sdk
    • Java binary at: /home/lithos/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/lithos/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
```

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [* ] Android
 - [ ] Browser

**Smartphone (please complete the following information):**
 - Device: Galaxy A50
 - OS: Android 9

**Comment by DavBfr** [comment]
Please test with the updated version.
