### ISSUE TITLE
PDF not accepting Indian currency symbol

### ISSUE THREAD

**Issue by ShrutiThakur01** [DavBfr/dart_pdf#220]
Hello I am using this to generate my invoice pdf.
Everything is working fine , except when i put my currency symbol its giving me exception.

below is how i am displaying it.

```
Text(
                            '₹ 20.01',
                            style: TextStyle(
                              fontSize: 10.0,
                              fontWeight: FontWeight.normal,
                            ),
                          ),
```
exception this code throwing is shown below,

```

E/flutter ( 5053): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:pdf/src/font.dart': Failed assertion: line 145 pos 14: 'false': 
E/flutter ( 5053): ---------------------------------------------
E/flutter ( 5053): Can not decode the string to Latin1.
E/flutter ( 5053): This font does not support Unicode characters.
E/flutter ( 5053): If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
E/flutter ( 5053): See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
E/flutter ( 5053): ---------------------------------------------
E/flutter ( 5053): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 5053): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 5053): #2      PdfFont.stringMetrics (package:pdf/src/font.dart:145:14)
E/flutter ( 5053): #3      RichText.layout.<anonymous closure> (package:pdf/widgets/text.dart:518:22)
E/flutter ( 5053): #4      TextSpan.visitChildren (package:pdf/widgets/text.dart:386:19)
E/flutter ( 5053): #5      RichText.layout (package:pdf/widgets/text.dart:498:10)
E/flutter ( 5053): #6      ConstrainedBox.layout (package:pdf/widgets/basic.dart:421:13)
E/flutter ( 5053): #7      StatelessWidget.layout (package:pdf/widgets/widget.dart:128:14)
E/flutter ( 5053): #8      Flex.layout (package:pdf/widgets/flex.dart:265:15)
E/flutter ( 5053): #9      Flex.layout (package:pdf/widgets/flex.dart:265:15)
E/flutter ( 5053): #10     Align.layout (package:pdf/widgets/basic.dart:305:13)
E/flutter ( 5053): #11     Padding.layout (package:pdf/widgets/basic.dart:84:13)
E/flutter ( 5053): #12     StatelessWidget.layout (package:pdf/widgets/widget.dart:128:14)
E/flutter ( 5053): #13     StatelessWidget.layout (package:pdf/widgets/widget.dart:128:14)
E/flutter ( 5053): #14     MultiPage.generate (package:pdf/widgets/multi_page.dart:218:13)
E/flutter ( 5053): #15     Document.addPage (package:pdf/widgets/document.dart:63:10)
E/flutter ( 5053): #16     generateInvoice (package:cmpic/widgets/generate_pdf.dart:11:7)
E/flutter ( 5053): #17     UserProfile.build.<anonymous closure> (package:cmpic/Pages/NavBar/userprofile.dart:162:31)
E/flutter ( 5053): #18     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5053): #19     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 5053): #20     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 5053): #21     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter ( 5053): #22     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5053): #23     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 5053): #24     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5053): #25     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5053): #26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5053): #27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5053): #28     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 5053): #29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5053): #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 5053): #31     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 5053): #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 5053): 
```

Thanks in advance.

**Comment by DavBfr** [comment]
See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by ShrutiThakur01** [comment]
Hello ,

thank you very very much for your help. that link solved my issue.  :)
can you help me with any link which i can refer to put my company logo in pdf? 

thanks in advance.

**Comment by DavBfr** [comment]
```dart
const imageProvider = const AssetImage('assets/image.png');
final PdfImage image = await pdfImageFromImageProvider(pdf: pdf.document, image: imageProvider);

pdf.addPage(Page(
    build: (Context context) {
      return Center(
        child: Image(image),
      ); // Center
    })); // Page
```

**Comment by ShrutiThakur01** [comment]
Thanks for help.
i used given code but i am getting below exception. pdfImageFromImageProvider function i copied and paste in my file from this link
https://pub.dev/documentation/printing/latest/printing/pdfImageFromImageProvider.html


```
E/flutter ( 6721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.
E/flutter ( 6721): #0      MultiPage.generate.<anonymous closure> (package:pdf/widgets/multi_page.dart:151:11)
E/flutter ( 6721): #1      MultiPage.generate (package:pdf/widgets/multi_page.dart:155:8)
E/flutter ( 6721): #2      Document.addPage (package:pdf/widgets/document.dart:63:10)
E/flutter ( 6721): #3      generateInvoice (package:cmpic/widgets/generate_pdf.dart:88:7)
E/flutter ( 6721): <asynchronous suspension>
E/flutter ( 6721): #4      UserProfile.build.<anonymous closure> (package:cmpic/Pages/NavBar/userprofile.dart:174:35)
E/flutter ( 6721): <asynchronous suspension>
E/flutter ( 6721): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6721): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6721): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6721): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter ( 6721): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 6721): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 6721): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6721): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6721): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6721): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6721): #15     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6721): #16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6721): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6721): #18     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 6721): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 6721): 
```

**Comment by DavBfr** [comment]
I can't help on this without the full source.

**Comment by ShrutiThakur01** [comment]
Hi,

below code i am using to generate and open pdf. I am calling this generateInvoice() function on button click.

i have attached link to show the output i am getting and i have highlighted the section where i am planning to put my company logo.

https://drive.google.com/file/d/1LEd9yY99rmtsVvyXSHT0FFTmxLI4aJYF/view?usp=sharing

```
import 'dart:async';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:cmpic/widgets/accounts.dart';
import 'package:flutter/painting.dart' as pi;
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';

final Document pdf = Document();

Future<PdfImage> pdfImageFromImage({PdfDocument pdf, ui.Image image}) async {
  final ByteData bytes =
  await image.toByteData(format: ui.ImageByteFormat.rawRgba);

  return PdfImage(pdf,
      image: bytes.buffer.asUint8List(),
      width: image.width,
      height: image.height);
}

Future<PdfImage> pdfImageFromImageProvider(
    {PdfDocument pdf,
      pi.ImageProvider image,
      pi.ImageConfiguration configuration,
      pi.ImageErrorListener onError}) async {
  final Completer<PdfImage> completer = Completer<PdfImage>();
  final pi.ImageStream stream =
  image.resolve(configuration ?? pi.ImageConfiguration.empty);

  pi.ImageStreamListener listener;
  listener = pi.ImageStreamListener((pi.ImageInfo image, bool sync) async {
    final PdfImage result =
    await pdfImageFromImage(pdf: pdf, image: image.image);
    if (!completer.isCompleted) {
      completer.complete(result);
    }
    stream.removeListener(listener);
  }, onError: (dynamic exception, StackTrace stackTrace) {
    if (!completer.isCompleted) {
      completer.complete(null);
    }
    if (onError != null) {
      onError(exception, stackTrace);
    } else {
      // https://groups.google.com/forum/#!topic/flutter-announce/hp1RNIgej38
      assert(false, 'image failed to load');
    }
  });

  stream.addListener(listener);
  return completer.future;
}

generateInvoice() async {
  const imageProvider = const pi.AssetImage('assets/applogo.png');
  final PdfImage image =
  await pdfImageFromImageProvider(pdf: pdf.document, image: imageProvider);

  var myTheme = Theme.withFont(
    base: Font.ttf(await rootBundle.load("assets/OpenSans-Regular.ttf")),
    bold: Font.ttf(await rootBundle.load("assets/OpenSans-Bold.ttf")),
    italic: Font.ttf(await rootBundle.load("assets/OpenSans-Italic.ttf")),
    boldItalic: Font.ttf(await rootBundle.load("assets/OpenSans-BoldItalic.ttf")),
  );

  pdf.addPage(MultiPage(
      theme: myTheme,
      pageFormat:
      PdfPageFormat.letter.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
      crossAxisAlignment: CrossAxisAlignment.start,
      header: (Context context) {

        return Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    SizedBox(height: 20.0),
                    Text(
                      'NAME OF COMPANY',
                      style: TextStyle(
                        fontSize: 10.0,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(height: 2.0),
                    Text('Maharashtra IN',
                        style: TextStyle(
                          fontSize: 8.0,
                          fontWeight: FontWeight.normal,
                        )),
                    SizedBox(height: 2.0),
                    Text('000000000',
                        style: TextStyle(
                          fontSize: 8.0,
                          fontWeight: FontWeight.normal,
                        )),
                    SizedBox(height: 2.0),
                    Text('dddd@fdgdg.com',
                        style: TextStyle(
                          fontSize: 8.0,
                          fontWeight: FontWeight.normal,
                        )),
                    SizedBox(height: 2.0),
                    Text('CIN: XYZ-12232',
                        style: TextStyle(
                          fontSize: 8.0,
                          fontWeight: FontWeight.normal,
                        )),
                    SizedBox(height: 30.0),
                  ]),
              Image(image, height: 10, width: 10),
            ]);
      },
      build: (Context context) => <Widget>[
        Header(
          level: 0,
          child: Column(
            children: <Widget>[
              Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'TAX INVOICE',
                      style: TextStyle(
                        fontSize: 14.0,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    Text(''),
                    //PdfLogo()
                  ]),
              SizedBox(height: 20.0),
              Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      'INVOICE TO',
                      style: TextStyle(
                        fontSize: 8.0,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Container(
                            width: 100,
                            child: Text(
                              'INVOICE NO.',
                              textAlign: TextAlign.right,
                              style: TextStyle(
                                fontSize: 8.0,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          Container(
                              width: 100,
                              child: Text(
                                '11646466',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                          Container(
                              width: 10,
                              child: Text(
                                '',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                        ]),
                  ]),
              SizedBox(height: 2.0),
              Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      'name',
                      style: TextStyle(
                        fontSize: 8.0,
                        fontWeight: FontWeight.normal,
                      ),
                    ),
                    Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Container(
                            width: 100,
                            child: Text(
                              'DATE ',
                              style: TextStyle(
                                fontSize: 8.0,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          Container(
                              width: 100,
                              child: Text(
                                '12/02/2020',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                          Container(
                              width: 10,
                              child: Text(
                                '',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                        ]),
                    //PdfLogo()
                  ]),
              SizedBox(height: 2.0),
              Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      "STATE: " ,
                      style: TextStyle(
                        fontSize: 8.0,
                        fontWeight: FontWeight.normal,
                      ),
                    ),
                    Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Container(
                            width: 100,
                            child: Text(
                              'TRANSACTION ID ',
                              style: TextStyle(
                                fontSize: 8.0,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          Container(
                              width: 100,
                              child: Text(
                                'YUYRUEYRUEY-YRY',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                          Container(
                              width: 10,
                              child: Text(
                                '',
                                style: TextStyle(
                                  fontSize: 8.0,
                                  fontWeight: FontWeight.normal,
                                ),
                              )),
                        ]),
                    //PdfLogo()
                  ]),
              SizedBox(height: 40.0),
            ],
          ),
        ),
      ]));

  final File file12 = await localFile;
  OpenFile.open(file12.path);
}

Future<String> get _localPath async {
  final directory = await getApplicationDocumentsDirectory();
  print("directory.path = " + directory.path);
  return directory.path;
}

Future<File> get localFile async {
  final path = await _localPath;
  print("path = " + path);
  final File file = File('$path/example12.pdf');
  file.writeAsBytesSync(pdf.save());
  return file;
}
```

**Comment by ShrutiThakur01** [comment]
Hello ,

hope this helps.. Let me know if anything else required from my side.

thanks .

**Comment by ShrutiThakur01** [comment]
Hi DavBf,

Awaiting your reply on this. 

TIA

**Comment by ShrutiThakur01** [comment]
Hi DavBf,

Awaiting your reply on this.

TIA

**Comment by DavBfr** [comment]
If you want to create multiple pages, a page break can occur only between one of the objects returned by the build callback.
```dart
build: (Context context) => <Widget>[
Text('line 1'),
Text('line 2'),
Text('line 3),
Text('line 4'),
Text('line 5'),
]
```

**Comment by ShrutiThakur01** [comment]
Hi DavBf,

thanks for your reply but I am not getting your point .. I want to generate only one page pdf with company logo in right top corner.This image is taken from generated pdf using this given code and only issue i am facing here is image. 
https://drive.google.com/file/d/1LEd9yY99rmtsVvyXSHT0FFTmxLI4aJYF/view?usp=sharing

Anything wrong in my code?

TIA

**Comment by DavBfr** [comment]
What's wrong with the image? I executed your code and have the same layout.

**Comment by ShrutiThakur01** [comment]
Problem is image is not getting displayed at all. without image code my pdf generating perfectly. 
once i put image code it's giving me below exception. 

> 
> **E/flutter ( 6721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.**
> E/flutter ( 6721): #0      MultiPage.generate.<anonymous closure> (package:pdf/widgets/multi_page.dart:151:11)
> E/flutter ( 6721): #1      MultiPage.generate (package:pdf/widgets/multi_page.dart:155:8)
> E/flutter ( 6721): #2      Document.addPage (package:pdf/widgets/document.dart:63:10)
> E/flutter ( 6721): #3      generateInvoice (package:cmpic/widgets/generate_pdf.dart:88:7)
> E/flutter ( 6721): <asynchronous suspension>
> E/flutter ( 6721): #4      UserProfile.build.<anonymous closure> (package:cmpic/Pages/NavBar/userprofile.dart:174:35)
> E/flutter ( 6721): <asynchronous suspension>
> E/flutter ( 6721): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> E/flutter ( 6721): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
> E/flutter ( 6721): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
> E/flutter ( 6721): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
> E/flutter ( 6721): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> E/flutter ( 6721): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
> E/flutter ( 6721): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> E/flutter ( 6721): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> E/flutter ( 6721): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> E/flutter ( 6721): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> E/flutter ( 6721): #15     _rootRunUnary (dart:async/zone.dart:1138:13)
> E/flutter ( 6721): #16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> E/flutter ( 6721): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
> E/flutter ( 6721): #18     _invoke1 (dart:ui/hooks.dart:273:10)
> E/flutter ( 6721): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
> E/flutter ( 6721):

**Comment by ShrutiThakur01** [comment]
okay finally i got it from another issue reported here and your comment on it.
https://github.com/DavBfr/dart_pdf/issues/109

> Thanks, yes, the app is killed by the OS because it used too much RAM:
> your jpeg image is big as jpeg, but the line: final PdfImage image = await pdfImageFromImageProvider(pdf: pdf.document, image: imageProvider);
> decodes it and get the uncompressed data, then keep it in RAM.
> When you call pdf.save() it compresses the binary data in memory.

After reading this comment i thought this might be an image size issue , so i used image below 10Kb and its working fine now. 

Thanks .
