### ISSUE TITLE
issue with Loading image to pdf

### ISSUE THREAD

**Issue by monkeyMax-SVG** [DavBfr/dart_pdf#287]
Hello.
I was trying to load image when i create pdf in flutter.

First, I took one image from image_picker (from camera) and then I tried to load that image to Pdf.

```dart
var pdf = new pw.Document();
var imagePath = "this is from image_picker camera";
final PdfImage image = await PdfImage.file(pdf.document, bytes: File(imagePath).readAsBytesSync(), orientation: PdfImageOrientation.bottomLeft);
pdf.addPage(pw.Page(
    build: (pw.Context context) {
      return pw.Center(
        child: pw.Image(image),
      ); // Center
    }));
```
issue occuered in this part
"final PdfImage image = await PdfImage.file(pdf.document, bytes: File(imagePath).readAsBytesSync(), orientation: PdfImageOrientation.bottomLeft);"

Following is issue
```
/data/data/com.jamie.billsender/cache/image_cropper_1588680703285.jpg
E/flutter (17185): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..7, inclusive: -1
E/flutter (17185): #0      List.[] (dart:core-patch/array.dart:168:52)
E/flutter (17185): #1      PdfJpegInfo.orientation (package:pdf/src/exif.dart:102:39)
E/flutter (17185): #2      new PdfImage.jpeg (package:pdf/src/image.dart:94:27)
E/flutter (17185): #3      new PdfImage.file (package:pdf/src/image.dart:137:23)
E/flutter (17185): #4      _BillhomeState._generatePdfAndView (package:billsender/billhome.dart:268:45)
```

**Flutter Doctor**
 `flutter doctor -v` here.
```
Flutter (Channel dev, v1.16.4-pre.132, on Mac OS X 10.15.4 19E287, locale
    en-CN)
    • Flutter version 1.16.4-pre.132 at /Users/kk/Developer/flutter
    • Framework revision 727552e5ca (4 weeks ago), 2020-04-06 13:38:41 -0700
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/kk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Users/kk/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)

```

**Comment by DavBfr** [comment]
Can you try to change the code for `exif.dart` line 99 with:

```dart
  PdfImageOrientation get orientation {
    if (tags == null || tags[PdfExifTag.Orientation] == null) {
      return PdfImageOrientation.topLeft;
    }

    try {
      return PdfImageOrientation.values[tags[PdfExifTag.Orientation] - 1];
    } on RangeError {
      return PdfImageOrientation.topLeft;
    }
  }
```

**Comment by monkeyMax-SVG** [comment]
Hi, @DavBfr  thank you for your response.
So you mean pub.dev/packages/pdf package has bug?

**Comment by DavBfr** [comment]
Not really. Apparently, your JPEG image contains an exif information with a non standard value for the orientation. This fix adds a mitigation.
If you confirm it fixes the issue I _will put that in the next version.

**Comment by monkeyMax-SVG** [comment]
> Can you try to change the code for `exif.dart` line 99 with:
> 
> ```dart
>   PdfImageOrientation get orientation {
>     if (tags == null || tags[PdfExifTag.Orientation] == null) {
>       return PdfImageOrientation.topLeft;
>     }
> 
>     try {
>       return PdfImageOrientation.values[tags[PdfExifTag.Orientation] - 1];
>     } on RangeError {
>       return PdfImageOrientation.topLeft;
>     }
>   }
> ```

This is perfect. It was fixed.
Thank you so much for your help.



> Not really. Apparently, your JPEG image contains an exif information with a non standard value for the orientation. This fix adds a mitigation.
> If you confirm it fixes the issue I _will put that in the next version.

Great.
