### ISSUE TITLE
Error: Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by Phil-Dunphy** [DavBfr/dart_pdf#291]
When I try to create a pdf in Flutter Web I become an error:

Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:65014/dart_sdk.js:4773:11)
    at Function._operatingSystem (http://localhost:65014/dart_sdk.js:51802:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:65014/dart_sdk.js:51851:27)
    at get _operatingSystem (http://localhost:65014/dart_sdk.js:51764:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:65014/dart_sdk.js:5267:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:65014/dart_sdk.js:51717:26)
    at LocalPlatform.get operatingSystem [as operatingSystem] (http://localhost:65014/packages/platform/src/interface/local_platform.dart.lib.js:19:26)
    at LocalPlatform.get isMacOS [as isMacOS] (http://localhost:65014/packages/platform/src/interface/platform.dart.lib.js:30:19)
    at method_channel_path_provider.MethodChannelPathProvider.new.getDownloadsPath (http://localhost:65014/packages/path_provider_platform_interface/src/method_channel_path_provider.dart.lib.js:141:38)
    at getDownloadsDirectory (http://localhost:65014/packages/path_provider/path_provider.dart.lib.js:78:49)
    at getDownloadsDirectory.next (<anonymous>)
    at runBody (http://localhost:65014/dart_sdk.js:35674:34)
    at Object._async [as async] (http://localhost:65014/dart_sdk.js:35702:7)
    at Object.getDownloadsDirectory (http://localhost:65014/packages/path_provider/path_provider.dart.lib.js:77:18)
    at createCLass._CreateClassState.new.savePdf (http://localhost:65014/packages/addlightweb/createCLass.dart.lib.js:450:53)
    at savePdf.next (<anonymous>)
    at runBody (http://localhost:65014/dart_sdk.js:35674:34)
    at Object._async [as async] (http://localhost:65014/dart_sdk.js:35702:7)
    at createCLass._CreateClassState.new.savePdf (http://localhost:65014/packages/addlightweb/createCLass.dart.lib.js:449:20)
    at createCLass._CreateClassState.new.<anonymous> (http://localhost:65014/packages/addlightweb/createCLass.dart.lib.js:459:36)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:65014/dart_sdk.js:35674:34)
    at Object._async [as async] (http://localhost:65014/dart_sdk.js:35702:7)
    at http://localhost:65014/packages/addlightweb/createCLass.dart.lib.js:457:719
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:65014/packages/flutter/src/gestures/recognizer.dart.lib.js:191:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:65014/packages/flutter/src/gestures/tap.dart.lib.js:355:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:65014/packages/flutter/src/gestures/tap.dart.lib.js:186:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:65014/packages/flutter/src/gestures/tap.dart.lib.js:164:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:65014/packages/flutter/src/gestures/arena.dart.lib.js:201:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:65014/packages/flutter/src/gestures/binding.dart.lib.js:170:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:65014/packages/flutter/src/gestures/binding.dart.lib.js:154:24)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:65014/packages/flutter/src/gestures/binding.dart.lib.js:131:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:65014/packages/flutter/src/gestures/binding.dart.lib.js:105:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:65014/packages/flutter/src/gestures/binding.dart.lib.js:96:65)
    at Object._invoke1 (http://localhost:65014/dart_sdk.js:159738:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:65014/dart_sdk.js:156917:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:65014/dart_sdk.js:137115:24)
    at http://localhost:65014/dart_sdk.js:137457:26
    at http://localhost:65014/dart_sdk.js:137422:16
    at http://localhost:65014/dart_sdk.js:137199:11

Did some one now how I can fix this?

**Comment by DavBfr** [comment]
Seems to be an issue with path_provider.

**Comment by NALAWALAMURTUZA** [comment]
how to resolve this @DavBfr

**Comment by NALAWALAMURTUZA** [comment]
after applying below solution it's working

https://stackoverflow.com/questions/62478134/flutter-path-provider-error-could-not-resolve-project-path-provider-linux
