### ISSUE TITLE
dose it support html?

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_pdf#327]
Hi as for now for RTL there is no support yet i want to build to see if its support html to PDF.?

**Comment by DavBfr** [comment]
Yes, it does!

**Comment by kw2019ltd** [comment]
can you guide to example? i dont see in demo folder any example or  i need to use printer plugin?

**Comment by DavBfr** [comment]
Yes, it's only printer plugin.

```dart
await Printing.layoutPdf(
    onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '<html><body><p>Hello!</p></body></html>',
        ));
```

**Comment by kw2019ltd** [comment]
cool will try it thanks.

**Comment by JoseGeorges8** [comment]
So I don't need to print a pdf but rather just display it. Will this html -> pdf work?

**Comment by Sun3** [comment]
Does the HTML Printing.layoutPdf() work on the web too?

Thank you.

**Comment by DavBfr** [comment]
@Sun3 yes!

**Comment by Sun3** [comment]
Thanks...

**Comment by Sun3** [comment]
@DavBfr I created a new test project but I am receiving the following error:

```
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:63567/dart_sdk.js:4339:11)
    at printing_web.PrintingPlugin.new.convertHtml (http://localhost:63567/packages/printing/src/printing_web.dart.lib.js:120:17)
    at Function.convertHtml (http://localhost:63567/packages/printing/src/printing.dart.lib.js:210:51)
    at http://localhost:63567/packages/pdf_print/main.dart.lib.js:447:44
    at Generator.next (<anonymous>)
    at runBody (http://localhost:63567/dart_sdk.js:37699:34)
    at Object._async [as async] (http://localhost:63567/dart_sdk.js:37730:7)
    at http://localhost:63567/packages/pdf_print/main.dart.lib.js:446:78
    at layoutPdf (http://localhost:63567/packages/printing/src/printing_web.dart.lib.js:74:29)
    at layoutPdf.next (<anonymous>)
    at runBody (http://localhost:63567/dart_sdk.js:37699:34)
    at Object._async [as async] (http://localhost:63567/dart_sdk.js:37730:7)
    at printing_web.PrintingPlugin.new.layoutPdf (http://localhost:63567/packages/printing/src/printing_web.dart.lib.js:72:20)
    at Function.layoutPdf (http://localhost:63567/packages/printing/src/printing.dart.lib.js:158:51)
    at _printHTMLtoPDF (http://localhost:63567/packages/pdf_print/main.dart.lib.js:446:33)
    at _printHTMLtoPDF.next (<anonymous>)
    at runBody (http://localhost:63567/dart_sdk.js:37699:34)
    at Object._async [as async] (http://localhost:63567/dart_sdk.js:37730:7)
    at main._MyHomePageState.new.[_printHTMLtoPDF] (http://localhost:63567/packages/pdf_print/main.dart.lib.js:445:20)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:63567/packages/flutter/src/material/icon_button.dart.lib.js:50678:42)
    at http://localhost:63567/packages/flutter/src/material/icon_button.dart.lib.js:50787:668
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:63567/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:63567/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:63567/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:63567/packages/flutter/src/gestures/tap.dart.lib.js:178:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:63567/packages/flutter/src/gestures/arena.dart.lib.js:208:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:310:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:289:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:63567/packages/flutter/src/rendering/layer.dart.lib.js:5973:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:260:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:233:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:222:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:63567/packages/flutter/src/gestures/binding.dart.lib.js:212:65)
    at Object._invoke1 (http://localhost:63567/dart_sdk.js:176547:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:63567/dart_sdk.js:172276:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:63567/dart_sdk.js:159053:24)
    at http://localhost:63567/dart_sdk.js:159442:26
    at http://localhost:63567/dart_sdk.js:159401:16
    at http://localhost:63567/dart_sdk.js:159154:11
```

index.html code:
```
<!DOCTYPE html>
<html>
<head>
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter application.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="pdf_print">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>pdf_print</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <!--  PDF Printing-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
  <script type="text/javascript">
     pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

main.dart sample code:
```
import 'package:flutter/material.dart';

// PDF Printing
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<void> _printHTMLtoPDF() async {
    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => await Printing.convertHtml(
          format: format,
          html: '<html><body><p>Hello!</p></body></html>',
        ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Print HTML to PDF:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _printHTMLtoPDF,
        tooltip: 'Create',
        child: Icon(Icons.picture_as_pdf),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```


Any thoughts on what I might be doing wrong?
Thank you.

**Comment by DavBfr** [comment]
Nothing wrong. Conversion from HTML to pdf is not supported on flutter-web.

**Comment by Sun3** [comment]
Got it. Do you think it will be supported in the future?

**Comment by DavBfr** [comment]
No, the browsers don't provide an API for that, and no Javascript library implements it either.

**Comment by Sun3** [comment]
Thanks...
