### ISSUE TITLE
Error: Exception: operation failed

### ISSUE THREAD

**Issue by tomasbaran** [DavBfr/dart_pdf#354]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
final doc = pw.Document();

    const imageProvider = const AssetImage('images/arrow_up.png');
    final PdfImage arrowUp = await pdfImageFromImageProvider(
      pdf: doc.document,
      image: imageProvider,
    );

doc.addPage(
      pw.Page(
        pageTheme: pageTheme,
        //pageFormat: PdfPageFormat.a5,
        build: (pw.Context context) => pw.Center(
          child: pw.Column(
            mainAxisAlignment: pw.MainAxisAlignment.center,
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
pw.Image(arrowUp),
],
          ),
        ),
      ),
    );
```

**Expected behavior**

**Screenshots**

**Error message**

```
Error: Exception: operation failed
    at Object.createErrorWithStack (http://localhost:64289/dart_sdk.js:4477:12)
    at Object._rethrow (http://localhost:64289/dart_sdk.js:37464:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64289/dart_sdk.js:37458:13)
    at Object._microtaskLoop (http://localhost:64289/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:64289/dart_sdk.js:37296:13)
    at http://localhost:64289/dart_sdk.js:32918:9Error: Exception: Image.toByteData is not supported in Flutter for Web
    at Object.throw_ [as throw] (http://localhost:64289/dart_sdk.js:4463:11)
    at Object.futurize (http://localhost:64289/dart_sdk.js:167435:17)
    at _engine.HtmlImage.new.toByteData (http://localhost:64289/dart_sdk.js:143503:22)
    at pdfImageFromImage (http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:31:32)
    at pdfImageFromImage.next (<anonymous>)
    at runBody (http://localhost:64289/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:64289/dart_sdk.js:37226:7)
    at Object.pdfImageFromImage (http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:30:18)
    at http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:46:41
    at Generator.next (<anonymous>)
    at runBody (http://localhost:64289/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:64289/dart_sdk.js:37226:7)
    at image_stream.ImageStreamListener.new.<anonymous> (http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:45:90)
    at image_stream.MultiFrameImageStreamCompleter.new.addListener (http://localhost:64289/packages/flutter/src/painting/image_stream.dart.lib.js:311:14)
    at image_stream.MultiFrameImageStreamCompleter.new.addListener (http://localhost:64289/packages/flutter/src/painting/image_stream.dart.lib.js:531:13)
    at image_stream.ImageStream.new.addListener (http://localhost:64289/packages/flutter/src/painting/image_stream.dart.lib.js:240:61)
    at pdfImageFromImageProvider (http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:61:14)
    at pdfImageFromImageProvider.next (<anonymous>)
    at runBody (http://localhost:64289/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:64289/dart_sdk.js:37226:7)
    at Object.pdfImageFromImageProvider (http://localhost:64289/packages/printing/src/asset_utils.dart.lib.js:40:18)
    at activation_screen3._ActivationScreen3State.new.downloadPdf (http://localhost:64289/packages/chefmenu/screens/passcode_screen.dart.lib.js:9437:42)
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ x] Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tomasbaran** [comment]
When I write it like this instead: 

```
final arrowUp = PdfImage.file(
      doc.document,
      bytes: File('images/arrow_up.png').readAsBytesSync(),
    );
```

then I get this error:

```
Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (http://localhost:64289/dart_sdk.js:4463:11)
    at Function.get _namespace [as _namespace] (http://localhost:64289/dart_sdk.js:53991:17)
    at io._File.new.openSync (http://localhost:64289/dart_sdk.js:51835:45)
    at io._File.new.readAsBytesSync (http://localhost:64289/dart_sdk.js:51898:25)
    at activation_screen3._ActivationScreen3State.new.downloadPdf (http://localhost:64289/packages/chefmenu/screens/passcode_screen.dart.lib.js:9410:98)
    at downloadPdf.next (<anonymous>)
    at http://localhost:64289/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:64289/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:64289/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:64289/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:64289/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:64289/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64289/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:64289/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:64289/dart_sdk.js:37296:13)
```

**Comment by tomasbaran** [comment]
When I write like this instead: 

```
 final response = await http.get('https://png.pngtree.com/png-clipart/20190705/original/pngtree-vector-up-arrow-icon-png-image_4231914.jpg');
    final arrowUp = PdfImage.file(
      doc.document,
      bytes: response.bodyBytes,
    );
```

I get this error:

```
rror: XMLHttpRequest error.
    dart:sdk_internal 124039:30                           get current
packages/http/src/browser_client.dart.lib.js 214:124  <fn>
dart:sdk_internal 37029:58                            runUnary
dart:sdk_internal 32116:29                            handleValue
dart:sdk_internal 32663:49                            handleValueCallback
dart:sdk_internal 32701:17                            _propagateToListeners
dart:sdk_internal 32535:25                            [_complete]
dart:sdk_internal 37439:24                            _cancelAndValue
dart:sdk_internal 18487:17                            <fn>
dart:sdk_internal 4673:16                             _checkAndCall
dart:sdk_internal 4678:17                             dcall
dart:sdk_internal 104576:23                           <fn>
    at Object.createErrorWithStack (http://localhost:64289/dart_sdk.js:4477:12)
    at Object._rethrow (http://localhost:64289/dart_sdk.js:37464:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64289/dart_sdk.js:37458:13)
    at Object._microtaskLoop (http://localhost:64289/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:64289/dart_sdk.js:37296:13)
```

**Comment by tomasbaran** [comment]
Btw, all I need is just a simple arrow_up and I have spent more than 2 hours on this and still no solution... :( 

Isn't there another way maybe much more simpler like using a special character or icon?

**Comment by DavBfr** [comment]
Use the Shape widget with the content of a SVG path:

```dart
Shape("'M 2.424 26.712 L 2.424 Z", width: 24, height: 27, fillColor: PdfColors.green)
```
