### ISSUE TITLE
No implementation found for method pickPrinter on channel net.nfet.printing on version 3.6.0

### ISSUE THREAD

**Issue by klavergne** [DavBfr/dart_pdf#400]
**Describe the bug**
Using printing version 3.6.0, the pickPrinter() method is not implemented. I tried this with 3.5.0, then upgraded to 3.6.0.

I get the following stack trace:
```
E/flutter (16794): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method pickPrinter on channel net.nfet.printing)
E/flutter (16794): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:159
E/flutter (16794): <asynchronous suspension>
E/flutter (16794): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:334
E/flutter (16794): #2      MethodChannelPrinting.pickPrinter 
package:printing/src/method_channel.dart:162
E/flutter (16794): #3      Printing.pickPrinter 
package:printing/src/printing.dart:54
E/flutter (16794): #4      _NewPartyScreenState._selectPrinter 
package:flutter_photobooth2/widgets/new_party_screen.dart:185
E/flutter (16794): #5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:992
E/flutter (16794): #6      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
E/flutter (16794): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
E/flutter (16794): #8      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
E/flutter (16794): #9      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
E/flutter (16794): #10     BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:219
E/flutter (16794): #11     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:477
E/flutter (16794): #12     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78
E/flutter (16794): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:124
E/flutter (16794): #14     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (16794): #15     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (16794): #16     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:108
E/flutter (16794): #17     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:220
E/flutter (16794): #18     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
E/flutter (16794): #19     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
E/flutter (16794): #20     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
E/flutter (16794): #21     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
E/flutter (16794): #22     _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter (16794): #23     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (16794): #24     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter (16794): #25     _invoke1  (dart:ui/hooks.dart:267:10)
E/flutter (16794): #26     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  Future<void> _selectPrinter() async {
    final printer = Printing.pickPrinter();
  }
```

**Expected behavior**
I would expect a printer selection screen to appear, given the documentation for the method.

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/klavergne/Documents/dev/flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/klavergne/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Pixel 3 XL (mobile) • 89WY0CSZ4 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3XL
 - OS: Android 10

**Comment by DavBfr** [comment]
This method exists only on iOS, it's not possible to select a printer and direct print using the Android API.

**Comment by klavergne** [comment]
It would be nice if you could update the documentation to state that. Or return a more helpful error. I assumed that it would work based on the documentation:
```dart
/// Opens the native printer picker interface, and returns the URL of the selected printer.
```

**Comment by DavBfr** [comment]
Good point. I'll add that.

**Comment by Manikandan88564** [comment]
> It would be nice if you could update the documentation to state that. Or return a more helpful error. I assumed that it would work based on the documentation:
> 
> ```dart
> /// Opens the native printer picker interface, and returns the URL of the selected printer.
> ```

it showing error in context 

Printer? pri = await Printing.pickPrinter(context: context);
