### ISSUE TITLE
Helvetica has no Unicode support

### ISSUE THREAD

**Issue by subair-zufi** [DavBfr/dart_pdf#405]
**Description of code**
I'm building a Job Application Web app with Flutter Web. I tried to get PDF formatted copy on submission. 
I tried
```import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

final pdf = pw.Document();

      pdf.addPage(pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Center(
              child: pw.Text(_postTitle),
            ); // Center
          }));
      final file = File("$applicationCode.pdf");
      await file.writeAsBytes(pdf.save());
```

**I'm getting**

```dart
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (http://localhost:46561/dart_sdk.js:4334:11)
    at Function.get _namespacePointer [as _namespacePointer] (http://localhost:46561/dart_sdk.js:54248:17)
    at Function._namespacePointer (http://localhost:46561/dart_sdk.js:51814:28)
    at Function._dispatchWithNamespace (http://localhost:46561/dart_sdk.js:51819:31)
    at io._File.new.open (http://localhost:46561/dart_sdk.js:51968:23)
    at io._File.new.writeAsBytes (http://localhost:46561/dart_sdk.js:52222:19)
    at apply_job_screen._ApplyJobScreenState.new._generatePdf (http://localhost:46561/packages/sirajulhuda_app/screens/apply_job_screen.dart.lib.js:8157:22)
    at _generatePdf.next (<anonymous>)
    at runBody (http://localhost:46561/dart_sdk.js:37623:34)
    at Object._async [as async] (http://localhost:46561/dart_sdk.js:37654:7)
    at _generatePdf (http://localhost:46561/packages/sirajulhuda_app/screens/apply_job_screen.dart.lib.js:8154:22)
    at apply_job_screen._ApplyJobScreenState.new._submitForm (http://localhost:46561/packages/sirajulhuda_app/screens/apply_job_screen.dart.lib.js:8189:13)
    at _submitForm.next (<anonymous>)
    at runBody (http://localhost:46561/dart_sdk.js:37623:34)
    at Object._async [as async] (http://localhost:46561/dart_sdk.js:37654:7)
    at ink_well._InkResponseStateWidget.new._submitForm (http://localhost:46561/packages/sirajulhuda_app/screens/apply_job_screen.dart.lib.js:8170:22)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:46561/packages/flutter/src/material/icon_button.dart.lib.js:46947:21)
    at http://localhost:46561/packages/flutter/src/material/icon_button.dart.lib.js:47049:668
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:46561/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:46561/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:46561/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:46561/packages/flutter/src/gestures/tap.dart.lib.js:148:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:46561/packages/flutter/src/gestures/recognizer.dart.lib.js:448:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:46561/packages/flutter/src/gestures/pointer_router.dart.lib.js:74:9)
    at http://localhost:46561/packages/flutter/src/gestures/pointer_router.dart.lib.js:109:26
    at LinkedMap.new.forEach (http://localhost:46561/dart_sdk.js:24760:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:46561/packages/flutter/src/gestures/pointer_router.dart.lib.js:106:29)
    at pointer_router.PointerRouter.new.route (http://localhost:46561/packages/flutter/src/gestures/pointer_router.dart.lib.js:98:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:46561/packages/flutter/src/gestures/binding.dart.lib.js:166:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:46561/packages/flutter/src/gestures/binding.dart.lib.js:149:24)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:46561/packages/flutter/src/gestures/binding.dart.lib.js:120:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:46561/packages/flutter/src/gestures/binding.dart.lib.js:93:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:46561/packages/flutter/src/gestures/binding.dart.lib.js:83:65)
    at Object._invoke1 (http://localhost:46561/dart_sdk.js:175339:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:46561/dart_sdk.js:171252:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:46561/dart_sdk.js:144583:24)
    at http://localhost:46561/dart_sdk.js:144970:26
    at http://localhost:46561/dart_sdk.js:144929:16
    at http://localhost:46561/dart_sdk.js:144682:11ERROR
```

**Expected behavior**
Download a file in pdf format

**Flutter Doctor**

```[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/koha/flutter
    • Framework revision be9bc8cb39 (8 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/koha/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/koha/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 4.0)
    • Android Studio at /home/koha/Applications/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 1 category.

```

**Desktop (please complete the following information):**
 - [x] Browser - Chrome (web)

**Comment by DavBfr** [comment]
You can's write to a file in a web browser. Nothing to do with the library.
`final file = File("$applicationCode.pdf");`

**Comment by BLUESYNTAX18** [comment]
Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by tehjinxi** [comment]
how you solve this problem? I encounter this issue as well @subair-zufi
