### ISSUE TITLE
True Type font not supported on Flutter Web

### ISSUE THREAD

**Issue by subair-zufi** [DavBfr/dart_pdf#412]
**Description**
Custom font not supported on flutter web

**I tried**
```dart
final Uint8List fontData = File('lib/fonts/trajan.ttf').readAsBytesSync();
  final ttf = pw.Font.ttf(fontData.buffer.asByteData());
Text(
              'My Text',
              style: pw.TextStyle(
                color: PdfColors.teal,
                font: ttf,
                fontWeight: pw.FontWeight.bold,
                fontSize: 22,
              ),
            )
```

**Error got**
```dart
Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (http://localhost:46799/dart_sdk.js:4334:11)
    at Function.get _namespace [as _namespace] (http://localhost:46799/dart_sdk.js:54245:17)
    at io._File.new.openSync (http://localhost:46799/dart_sdk.js:52089:45)
    at io._File.new.readAsBytesSync (http://localhost:46799/dart_sdk.js:52152:25)
    at widgets.MultiPage.new._header (http://localhost:46799/packages/sirajulhuda_app/functions/pdf.dart.lib.js:150:57)
    at widgets.MultiPage.new.generate (http://localhost:46799/packages/pdf/widgets.dart.lib.js:8893:54)
    at widgets.Document.new.addPage (http://localhost:46799/packages/pdf/widgets.dart.lib.js:6189:12)
    at generatePdf (http://localhost:46799/packages/sirajulhuda_app/functions/pdf.dart.lib.js:126:11)
    at generatePdf.next (<anonymous>)
    at runBody (http://localhost:46799/dart_sdk.js:37623:34)
    at Object._async [as async] (http://localhost:46799/dart_sdk.js:37654:7)
    at Object.generatePdf (http://localhost:46799/packages/sirajulhuda_app/functions/pdf.dart.lib.js:123:18)
    at http://localhost:46799/packages/sirajulhuda_app/functions/print_data_parser.dart.lib.js:49:13
    at _RootZone.runUnary (http://localhost:46799/dart_sdk.js:37457:58)
    at _FutureListener.then.handleValue (http://localhost:46799/dart_sdk.js:32441:29)
    at handleValueCallback (http://localhost:46799/dart_sdk.js:32988:49)
    at Function._propagateToListeners (http://localhost:46799/dart_sdk.js:33026:17)
    at _Future.new.[_completeWithValue] (http://localhost:46799/dart_sdk.js:32869:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:46799/dart_sdk.js:32891:35)
    at Object._microtaskLoop (http://localhost:46799/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:46799/dart_sdk.js:37724:13)
    at http://localhost:46799/dart_sdk.js:33243:9
```

**Flutter Doctor**

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/koha/flutter
    • Framework revision be9bc8cb39 (13 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/koha/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/koha/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 4.0)
    • Android Studio at /home/koha/Applications/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 1 category.
```

**Desktop :**
 - [ ] Browser - Chrome

**Comment by DavBfr** [comment]
You cannot use File() on web, a web browser has no file system access.
use assets or CDN instead.

**Comment by imakevirtual** [comment]
> You cannot use File() on web, a web browser has no file system access.
> use assets or CDN instead.

Can you please post a code sample for that?

**Comment by DavBfr** [comment]
@imakevirtual look at this page: https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by imakevirtual** [comment]
> @imakevirtual look at this page: https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

Thank you very much, it's a lot for me.

**Comment by sgissinger** [comment]
I use [Flutter assets](https://flutter.dev/docs/development/ui/assets-and-images) and it works on Flutter Web.

```dart
final ByteData fontData = await rootBundle.load('assets/fonts/trajan.ttf');
final ttf = pw.Font.ttf(fontData);
```
