### ISSUE TITLE
Exception on layoutPdf

### ISSUE THREAD

**Issue by calmh** [DavBfr/dart_pdf#42]
I have to admit I seem to be a bit unlucky. Following #41 I'm building with the following quick example:

```
Widget build(BuildContext ctx) {
    return Center(
      child: FlatButton(
        child: Text("Build"),
        onPressed: () async {
          Printing.layoutPdf(onLayout: (_) {
            return generatePDF(state);
          });
          // Directory appDocDir = await getApplicationDocumentsDirectory();
          // String appDocPath = appDocDir.path;
          // File file = File(appDocPath + "/test.pdf");
          // await file.writeAsBytes(pdf);
        },
      ),
    );
  }
```

where `generatePDF(state)` is your example PDF code. (This results in a perfectly fine PDF when saved to a file using the commented out code above instead of running Printing.)

However, when run in flutter the above generates:

```
Tried calling: invokeMethod<void>("printPdf", _LinkedHashMap len:1)
Found: invokeMethod(String, [dynamic]) => Future<dynamic>
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Printing.layoutPdf 
../…/src/printing.dart:52
<asynchronous suspension>
#2      PDFWidget.build.<anonymous closure> 
package:RWYRA/…/pdf/pdf.dart:23
<asynchronous suspension>
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:507
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:562
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:102
#6      TapGestureRecognizer._checkUp (package:flutter/<…>
```

Similarly, if I try just `Printing.sharePdf(bytes: generatePDF(state));` this gives

```
Tried calling: invokeMethod<void>("sharePdf", _LinkedHashMap len:6)
Found: invokeMethod(String, [dynamic]) => Future<dynamic>
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Printing.sharePdf 
../…/src/printing.dart:89
<asynchronous suspension>
#2      PDFWidget.build.<anonymous closure> 
package:RWYRA/…/pdf/pdf.dart:23
<asynchronous suspension>
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:507
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:562
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:102
#6      TapGestureRecognizer._checkUp (package:flutter/s<…>
```

Am I missing something obvious?

**Comment by DavBfr** [comment]
I tested with:
```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
      child: FlatButton(
        child: Text("Build"),
        onPressed: () async {
          Printing.layoutPdf(onLayout: (PdfPageFormat format) {
            final pdf = Pdf.Document()
              ..addPage(Pdf.Page(
                  pageFormat: format,
                  build: (Pdf.Context context) {
                    return Pdf.Center(
                      child: Pdf.Text("Hello World"),
                    ); // Center
                  }));
            return pdf.document.save();
          });
          // Directory appDocDir = await getApplicationDocumentsDirectory();
          // String appDocPath = appDocDir.path;
          // File file = File(appDocPath + "/test.pdf");
          // await file.writeAsBytes(pdf);
        },
      ),
    ),
    );
  }
```

Just add the right imports:
```dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as Pdf;
import 'package:printing/printing.dart';
```

**Comment by calmh** [comment]
I get the same exception by replacing my main widget with just the above. I'll see what happens in a new project that doesn't have a bunch of other "baggage" already in it...

**Comment by calmh** [comment]
I created this sample: https://github.com/calmh/printingtest

That's "flutter create" followed by adding the above code, the dependencies, and the tweaks to the Pdfile. Upon running and clicking the button it dies with

```
#2      _MyHomePageState.build.<anonymous closure> 
package:printingtest/main.dart:75
<asynchronous suspension>
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:507
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:562
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:102
#6      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:242
#7      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:175
#8      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:315
#9      PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:73
#10     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:101
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:180
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:158
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:138
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:101
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:85
#16     _invoke1 (dart:ui/hooks.dart:168:13)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

Do you have a self contained example that does work, that I could compare to?

**Comment by DavBfr** [comment]
This one is supposed to work:
https://github.com/DavBfr/dart_pdf/tree/master/printing/example

**Comment by DavBfr** [comment]
I just published version 1.3.4, I hope it will fix your issues.

**Comment by calmh** [comment]
Hmm, I don't see much of a difference unfortunately. Cloning your repo and running `flutter run` in `printing/example` results in a similar exception:

```
jb@kvin:~/t/d/p/example $ flutter run
Running "flutter packages get" in example...                 3.6s
Launching lib/main.dart on Jakob Borg’s iPad in debug mode...
Upgrading project.pbxproj of Runner.app' to include the 'flutter_assets' directory
Multiple valid development certificates available (your choice will be saved):
  1) iPhone Developer: Jakob Borg (TDGVNCLG6S)
  2) iPhone Developer: Jakob Borg (544PYLHCNP)
  a) Abort
Please select a certificate for code signing [1|2|a]: 1
Certificate choice "iPhone Developer: Jakob Borg (TDGVNCLG6S)" saved
Signing iOS app for device deployment using developer identity: "iPhone Developer: Jakob Borg (TDGVNCLG6S)"

Running pod install...                                       1.0s
Starting Xcode build...
 ├─Assembling Flutter resources...                    3.9s

Xcode build done.                                            7.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===

    Compiler message:
    file:///Users/jb/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/printing-1.3.4/lib/src/printing.dart:39:24: Error: Expected 0
    type arguments.
            await _channel.invokeMethod<void>('writePdf', params);
                           ^
    file:///Users/jb/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/printing-1.3.4/lib/src/printing.dart:52:20: Error: Expected 0
    type arguments.
        await _channel.invokeMethod<void>('printPdf', params);
                       ^
    file:///Users/jb/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/printing-1.3.4/lib/src/printing.dart:89:20: Error: Expected 0
    type arguments.
        await _channel.invokeMethod<void>('sharePdf', params);
                       ^
    Compiler failed on /Users/jb/tmp/dart_pdf/printing/example/lib/main.dart
    Failed to package /Users/jb/tmp/dart_pdf/printing/example.

Could not build the precompiled application for the device.

Error launching application on Jakob Borg’s iPad.
 4.7s
```

Does this really work for you, out of the box? Recent Xcode, flutter 1.0.0, etc?

**Comment by DavBfr** [comment]
Can you give me the output of `flutter doctor -v`?

**Comment by calmh** [comment]
```
jb@kvin:~/t/d/p/example $ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.0.0 at /Users/jb/sdk/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/jb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • Jakob Borg’s iPad • e16f9335b8c571b4390878e3313900bf6a035d53 • ios • iOS 12.1.4

! Doctor found issues in 3 categories.
```

**Comment by DavBfr** [comment]
a quickfix would be to run:
```shell
flutter channel master
flutter upgrade
```

**Comment by calmh** [comment]
OK. Going up to the beta channel was sufficient to resolve. Thanks.

**Comment by calmh** [comment]
By the way this is awesome now that it works. Thank you for creating, releasing, maintaining and support this!
