### ISSUE TITLE
This widget created more than 20 pages. This may be an issue in the widget or the document.

### ISSUE THREAD

**Issue by curlyeto** [DavBfr/dart_pdf#461]
**Explanation**

I want to create a table in pdf and put the records list in my hand. It is a single page, but when the page is finished I want the remaining elements of the list to appear on the next page. I used MultiPage for this but I am getting an error. 13 elements fit in one page

https://github.com/DavBfr/dart_pdf/blob/master/demo/lib/invoice.dart 

I got refans from the example here

**Error**
This widget created more than 20 pages. This may be an issue in the widget or the document.
```dart
E/flutter (19957): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.
E/flutter (19957): #0      MultiPage.generate.<anonymous closure> (package:pdf/widgets/multi_page.dart:185:11)
E/flutter (19957): #1      MultiPage.generate (package:pdf/widgets/multi_page.dart:189:8)
E/flutter (19957): #2      Document.addPage (package:pdf/widgets/document.dart:65:10)
E/flutter (19957): #3      _TableShowState.createPdf (package:covid19_manager/tableshow.dart:217:9)
E/flutter (19957): #4      _TableShowState.build.<anonymous closure> (package:covid19_manager/tableshow.dart:111:39)
E/flutter (19957): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (19957): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (19957): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (19957): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (19957): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (19957): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (19957): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (19957): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (19957): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (19957): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (19957): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (19957): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (19957): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (19957): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (19957): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (19957): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (19957): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (19957): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (19957): #23     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (19957): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
```

**Code**

```dart
  Future<String> createPdf() async{
    PdfColor white= PdfColor.fromInt(0xffffff);
    final pdf = pw.Document();
    const tableHeaders = [
      'Giris Tarih',
      'Cikis Tarih',
      'Ad',
      'Soyad',
      'Adres',
      'Posta Kodu',
      'Sehir',
      'Telefon',
    ];
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context)=>[
          pw.Column(
              mainAxisAlignment:  pw.MainAxisAlignment.start,
              children: [
                pw.Table.fromTextArray(
                  cellAlignment: pw.Alignment.centerLeft,
                  headerDecoration: pw.BoxDecoration(
                    borderRadius: 2,
                  ),
                  headerHeight: 25,
                  cellHeight: 40,
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.centerLeft,
                    2: pw.Alignment.centerLeft,
                    3: pw.Alignment.centerLeft,
                    4: pw.Alignment.centerLeft,
                    5: pw.Alignment.centerLeft,
                    6: pw.Alignment.centerLeft,
                    7: pw.Alignment.centerLeft,
                  },
                  headerStyle: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                  ),
                  cellStyle: const pw.TextStyle(
                    fontSize: 9,
                  ),
                  rowDecoration: pw.BoxDecoration(
                    border: pw.BoxBorder(
                      bottom: true,
                      width: .8,
                    ),
                  ),
                  headers: List<String>.generate(
                    tableHeaders.length,
                        (col) => tableHeaders[col],
                  ),
                  data: List<List<String>>.generate(
                    records.length,
                        (row) => List<String>.generate(
                      tableHeaders.length,
                          (col) => records[row].getIndex(col),
                    ),
                  ),
                ),
              ]
          ),

        ]
      )
    );
    Directory appDocDir = await getApplicationDocumentsDirectory();
    String appDocPath = appDocDir.path;
    final file = File("$appDocPath/raporlar.pdf");
    var abc=await file.writeAsBytes(pdf.save());
    return file.path;
  }
```

**Comment by DavBfr** [comment]
Remove the first column widget.

**Comment by zgramming** [comment]
Same issue .  
I have data `Map<String,List<PersonModel>>`  with total data 24 like this : 

```
{Group 1: [PersonModel(id: 24, name: Ilham), PersonModel(id: 10, name: Raka), PersonModel(id: 9, name: Ricky), PersonModel(id: 17, name: Afif), PersonModel(id: 15, name: Rayhan), PersonModel(id: 7, name: Syarif), PersonModel(id: 11, name: Rheiza), PersonModel(id: 19, name: Ahyar), PersonModel(id: 14, name: Danang), PersonModel(id: 23, name: Fauzan), PersonModel(id: 18, name: Anggit), PersonModel(id: 21, name: Ipul), PersonModel(id: 2, name: Fani), PersonModel(id: 1, name: Zeffry), PersonModel(id: 5, name: Rifda), PersonModel(id: 8, name: Helmi), PersonModel(id: 20, name: Umar), PersonModel(id: 22, name: Yogi), PersonModel(id: 12, name: Alex), PersonModel(id: 6, name: Kurniati), PersonModel(id: 13, name: Ivan), PersonModel(id: 16, name: Andi), PersonModel(id: 3, name: intan), PersonModel(id: 4, name: nakia)]}
```
And my layout like this : 

```
static Future<void> printPDF(Map<String, List<PersonModel>> generateResult) async {
    print(generateResult);
    var myTheme = pw.ThemeData.withFont(
      base: pw.Font.ttf(await rootBundle.load("assets/fonts/body/Poppins-Medium.ttf")),
      bold: pw.Font.ttf(await rootBundle.load("assets/fonts/body/Poppins-Regular.ttf")),
    );

    final pw.Document _pdf = pw.Document(theme: myTheme);

    _pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter.copyWith(marginBottom: 1.5 * PdfPageFormat.cm),
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        build: (ctx) => <pw.Widget>[
          ...generateResult.entries.map((e) {
            final nameGroup = e.key;
            final persons = e.value;
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  nameGroup,
                  style: pw.TextStyle(fontSize: 34.0),
                ),
                pw.SizedBox(height: 10),
                pw.Container(
                  decoration: pw.BoxDecoration(
                    borderRadius: 15,
                    border: pw.BoxBorder(),
                  ),
                  child: pw.ListView.builder(
                    itemCount: persons.length,
                    itemBuilder: (context, index) {
                      final person = persons[index];
                      return pw.Padding(
                        padding: const pw.EdgeInsets.symmetric(horizontal: 12.0),
                        child: pw.Column(
                          children: [
                            pw.SizedBox(height: 10),
                            pw.Row(
                              children: [
                                pw.Flexible(child: pw.Text('${index + 1}.')),
                                pw.Flexible(
                                  fit: pw.FlexFit.tight,
                                  child: pw.Padding(
                                    padding: pw.EdgeInsets.symmetric(horizontal: 8.0),
                                    child: pw.Text(person.name),
                                  ),
                                ),
                              ],
                            ),
                            pw.SizedBox(height: 10),
                            if ((index + 1) < persons.length) pw.Divider(thickness: 1),
                          ],
                        ),
                      );
                    },
                  ),
                ),
                pw.SizedBox(height: 20),
              ],
            );
          }).toList(),
        ],
        footer: (context) {
          return pw.Text(' --- ');
        },
      ),
    );
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/kelompok-generator.pdf");
    await file.writeAsBytes(_pdf.save());
    print(file.path);
    await Share.shareFiles(
      [
        file.path,
      ],
      text: 'PDF generate kelompok',
    );
  }
```

**Comment by DavBfr** [comment]
You try to draw a border around the group of peoples, but it's not possible to cut that at a page boundary. So one group of users will result in a widget bigger than a page and cannot be layed out.

**Comment by zgramming** [comment]
@DavBfr already remove border on Container ,nothing happen. So i re-code to check if length of list > 15 , i use gridview : 

```
 static Future<void> printPDF(Map<String, List<PersonModel>> generateResult) async {
    print(generateResult);
    var myTheme = pw.ThemeData.withFont(
      base: pw.Font.ttf(await rootBundle.load("assets/fonts/body/Poppins-Medium.ttf")),
      bold: pw.Font.ttf(await rootBundle.load("assets/fonts/body/Poppins-Regular.ttf")),
    );

    final pw.Document _pdf = pw.Document(theme: myTheme);

    _pdf.addPage(
      pw.MultiPage(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        build: (ctx) => <pw.Widget>[
          ...generateResult.entries.map((e) {
            final nameGroup = e.key;
            final persons = e.value;
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  nameGroup,
                  style: pw.TextStyle(fontSize: 20.0),
                ),
                pw.SizedBox(height: 10),
                if (persons.length > 15) ...[
                  pw.GridView(
                    crossAxisCount: 4,
                    children: persons.asMap().entries.map(
                      (e) {
                        final index = e.key + 1;
                        final person = e.value;
                        return pw.Text(
                          '$index. ${person.name}',
                          textAlign: pw.TextAlign.center,
                          maxLines: 1,
                        );
                      },
                    ).toList(),
                    padding: pw.EdgeInsets.all(20),
                    childAspectRatio: .5,
                  )
                ] else ...[
                  pw.ListView.builder(
                    itemCount: persons.length,
                    itemBuilder: (context, index) {
                      final person = persons[index];
                      return pw.Padding(
                        padding: const pw.EdgeInsets.symmetric(horizontal: 12.0),
                        child: pw.Column(
                          children: [
                            pw.Row(
                              children: [
                                pw.Flexible(child: pw.Text('${index + 1}.')),
                                pw.Flexible(
                                  fit: pw.FlexFit.tight,
                                  child: pw.Padding(
                                    padding: pw.EdgeInsets.symmetric(horizontal: 8.0),
                                    child: pw.Text(person.name, maxLines: 1),
                                  ),
                                ),
                              ],
                            ),
                            pw.SizedBox(height: 10),
                            if ((index + 1) < persons.length) pw.Divider(thickness: 1),
                          ],
                        ),
                      );
                    },
                  ),
                ],
                pw.SizedBox(height: 20),
              ],
            );
          }).toList(),
        ],
        footer: (context) {
          return pw.Text(
            '${GlobalFunction.formatYearMonthDay(DateTime.now())} | ${GlobalFunction.formatHoursMinutesSeconds(DateTime.now())}',
          );
        },
      ),
    );
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/kelompok-generator.pdf");
    await file.writeAsBytes(_pdf.save());
    print(file.path);
    await Share.shareFiles(
      [
        file.path,
      ],
      text: 'PDF generate kelompok',
      subject: 'Gunakan PDF ini sebaik mungkin ya...',
    );
  }
```

# Result

### Listview - view
![listview-view](https://user-images.githubusercontent.com/38829404/98196498-dc622480-1f56-11eb-99da-30cfb0e8feb9.jpeg)


### Gridview - view
![gridview-view](https://user-images.githubusercontent.com/38829404/98196504-e08e4200-1f56-11eb-936b-e1f124b6099c.jpeg)


But my question is , possible if i only use Listview and not get the error  ?

**Comment by curlyeto** [comment]
@DavBfr  thank you. Problem solved.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
