### ISSUE TITLE
I have problem , when i try to generate a file pdf 

### ISSUE THREAD

**Issue by HasseneKh** [DavBfr/dart_pdf#479]
**Describe the bug**
i have problem  when i try to generate a file pdf  
with 
```yml
pdf: ^1.12.0
```

```dart
   final File file = File(filepath);
    file.writeAsBytesSync(pdf.save());
```

```bash
NoSuchMethodError: The getter 'codeUnits' was called on null.
Receiver: null
Tried calling: codeUnits #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _stringToUtf16CodeUnits (package:utf/src/utf16.dart:213:41)
#2      encodeUtf16be (package:utf/src/utf16.dart:146:30)
#3      PdfString._string (package:pdf/src/data_types.dart:113:53)
#4      new PdfSecString.fromString (package:pdf/src/data_types.dart:206:43)
#5      PdfAnnotUrlLink.build (package:pdf/src/annotation.dart:222:30)
#6      PdfAnnot._prepare (package:pdf/src/annotation.dart:40:11)
#7      PdfObject._write (package:pdf/src/object.dart:53:5)
#8      PdfOutput.write (package:pdf/src/output.dart:69:8)
#9      SetMixin.forEach (dart:collection/set.dart:142:30)
#10     PdfDocument._write (package:pdf/src/document.dart:179:13)
#11     PdfDocument.save (package:pdf/src/document.dart:187:5)
#12     Document.save (package:pdf/widgets/document.dart:76:21)
#13     PDFGenerator._generateSortirPDF (package:sv_rent_car/utils/pdf/pdf_generator.dart:292:31)
#14     PDFGenerator.generateSortir (package:sv_rent_car/utils/pdf/pdf_generator.dart:55:5)
#15     DocumentRepository.generateSortirDocument (package:sv_rent_car/src/repositories/document_repository.dart:19:9)
#16     ContractRepository.insert (package:sv_rent_car/src/repositories/contract_repository.dart:291:51)
<asynchronous suspension>```




**Flutter Doctor**
```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.89, on Mac OS X 10.15.7 19H2, locale fr-TN)
    • Flutter version 1.22.0-10.0.pre.89 at /Users/hassene/Documents/flutter
    • Framework revision 0bb1e573fc (3 months ago), 2020-09-08 15:28:13 +0200
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hassene/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/hassene/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/hassene/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
```

**Comment by DavBfr** [comment]
Looks like you're trying to create a link to a website, but the URL is null
