### ISSUE TITLE
The following assertion was thrown when reporting an error to an image listener: image failed to load 'package:printing/src/asset_utils.dart':

### ISSUE THREAD

**Issue by nilsreichardt** [DavBfr/dart_pdf#511]
**Describe the bug**
I try to use `flutterImageProvider` with `Uint8List`, but it fails. It's a valid image. It can be displayed by flutter:

![image](https://user-images.githubusercontent.com/24459435/103486541-d8d80600-4dfe-11eb-8982-7c9a19f1f67a.png)

**Code to display image**
```
import 'dart:typed_data';
import 'package:flutter/material.dart';

main() => runApp(MaterialApp(home: Demo()));

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Image')),
      body: Image.memory(Uint8List.fromList([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 1, 0, 0, 0, 1, 0, 1, 3, 0, 0, 0, 102, 188, 58, 37, 0, 0, 0, 3, 80, 76, 84, 69, 181, 208, 208, 99, 4, 22, 234, 0, 0, 0, 31, 73, 68, 65, 84, 104, 129, 237, 193, 1, 13, 0, 0, 0, 194, 160, 247, 79, 109, 14, 55, 160, 0, 0, 0, 0, 0, 0, 0, 0, 190, 13, 33, 0, 0, 1, 154, 96, 225, 213, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130])),
    );
  }
}
```

But if I use `flutterImageProvider` I get this exception:
```
The following assertion was thrown when reporting an error to an image listener:
image failed to load
'package:printing/src/asset_utils.dart':
Failed assertion: line 105 pos 14: 'false'
```

**Code to reproduce**
```
test('test image', () async {
      final bytes = Uint8List.fromList([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 1, 0, 0, 0, 1, 0, 1, 3, 0, 0, 0, 102, 188, 58, 37, 0, 0, 0, 3, 80, 76, 84, 69, 181, 208, 208, 99, 4, 22, 234, 0, 0, 0, 31, 73, 68, 65, 84, 104, 129, 237, 193, 1, 13, 0, 0, 0, 194, 160, 247, 79, 109, 14, 55, 160, 0, 0, 0, 0, 0, 0, 0, 0, 190, 13, 33, 0, 0, 1, 154, 96, 225, 213, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130]);
      final imageProvider = Image.memory(bytes).image;
      expect(await flutterImageProvider(imageProvider), isNotNull);
    });
```

Link to image: https://www.mjt.me.uk/assets/images/smallest-png/openstreetmap.png

**Comment by DavBfr** [comment]
I have no issues with your example, it's working as expected.

```dart
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() => runApp(const MyApp('Printing Demo'));

class MyApp extends StatelessWidget {
  const MyApp(this.title);

  final String title;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text(title)),
        body: PdfPreview(
          build: _generatePdf,
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();

    final bytes = Uint8List.fromList([
      137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 1, //
      0, 0, 0, 1, 0, 1, 3, 0, 0, 0, 102, 188, 58, 37, 0, 0, 0, 3, 80, 76, 84,
      69, 181, 208, 208, 99, 4, 22, 234, 0, 0, 0, 31, 73, 68, 65, 84, 104,
      129, 237, 193, 1, 13, 0, 0, 0, 194, 160, 247, 79, 109, 14, 55, 160, 0, 0,
      0, 0, 0, 0, 0, 0, 190, 13, 33, 0, 0, 1, 154, 96, 225, 213, 0, 0, 0, 0, 73,
      69, 78, 68, 174, 66, 96, 130
    ]);

    final im = await flutterImageProvider(Image.memory(bytes).image);

    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Center(
            child: pw.Image.provider(im),
          );
        },
      ),
    );

    return pdf.save();
  }
}
```

**Comment by nilsreichardt** [comment]
Try to run this code in a test file:

```
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:printing/printing.dart';

void main() {
  test('test image', () async {
    final bytes = Uint8List.fromList([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 1, 0, 0, 0, 1, 0, 1, 3, 0, 0, 0, 102, 188, 58, 37, 0, 0, 0, 3, 80, 76, 84, 69, 181, 208, 208, 99, 4, 22, 234, 0, 0, 0, 31, 73, 68, 65, 84, 104, 129, 237, 193, 1, 13, 0, 0, 0, 194, 160, 247, 79, 109, 14, 55, 160, 0, 0, 0, 0, 0, 0, 0, 0, 190, 13, 33, 0, 0, 1, 154, 96, 225, 213, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130]);
    final imageProvider = Image.memory(bytes).image;
    expect(await flutterImageProvider(imageProvider), isNotNull);
  });
}
```

Filename: `printing_test.dart`
Version: `4.0.0`

I get this error:
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown when reporting an error to an image listener:
image failed to load
'package:printing/src/asset_utils.dart':
Failed assertion: line 56 pos 14: 'false'

When the exception was thrown, this was the stack:
#2      flutterImageProvider.<anonymous closure> (package:printing/src/asset_utils.dart:56:14)
#3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:686:24)
#4      _ErrorImageCompleter.setError (package:flutter/src/painting/image_provider.dart:1128:5)
#5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:353:24)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════
Expected: not null
  Actual: <null>

package:test_api                                   expect
expect
package:flutter_test/src/widget_tester.dart:429
main.<fn>
test/printing_test.dart:11
2

✖ test image
Exited (1)
```

**Comment by DavBfr** [comment]
Still working. I tested with Flutter 1.22.5 _stable_ and Flutter 1.26.0-1.0.pre _dev_

<img width="689" alt="Screen Shot 2021-01-09 at 10 14 00" src="https://user-images.githubusercontent.com/1387855/104093841-36cf7800-525b-11eb-915e-a7fb752f2d9b.png">
