### ISSUE TITLE
How to add an Image in the table

### ISSUE THREAD

**Issue by NiroopNife** [DavBfr/dart_pdf#545]
How to add an Image/Icon in one of the column of the table? In the product class I'm adding the IconData object and initializing it in the constructor but I'm getting an error stating as **Unhandled Exception: type 'IconData' is not a subtype of type 'String'**

This is the model call which I've used
```
class Product {
  const Product(this.serial,
      this.articleNumber,
      this.addresseeName,
      this.remark,
      this.iconData;
      );

  final String serial;
  final String articleNumber;
  final String addresseeName;
  final String remark;
  final IconData iconData;


  getIndex(int index) {
    switch (index) {
      case 0:
        return serial;
      case 1:
        return articleNumber;
      case 2:
        return addresseeName;
      case 3:
        return remark.toString();
      case 4:
        return iconData;;
    }
    return '';
  }

}
```

This is the data which I'm tring to insert into the table
```
final products = <Product>[
    Product('1', 'RK1234567890IN', '', 'NOT DELIVERED', Icons.ac_unit),
    Product('2', 'RM0987654321IN', 'Ramesh', 'DELIVERED \n ( To : name)\n29-01-2021 10:03:43', Icons.ac_unit),
    Product('3', 'RL4345424741IN', 'Suresh', 'DELIVERED \n ( To : name)\n29-01-2021 10:30:13', Icons.ac_unit),
    Product('4', 'RO9638642753IN', '', 'NOT DELIVERED', Icons.ac_unit),
  ];
```

& this is how I have initialized the table
```
pw.Widget _contentArticleTable(pw.Context context) {
    const tableHeaders = [
      'SERIAL',
      'ARTICLE NUMBER',
      'ADDRESSEE NAME',
      'REMARK',
      'SIGNATURE'
    ];
    return pw.Table.fromTextArray(
      cellAlignment: pw.Alignment.centerLeft,
      headerDecoration: pw.BoxDecoration(
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(2)),
        color: PdfColors.grey200,
      ),
      headerHeight: 25,
      cellHeight: 40,
      cellAlignments: {
        0: pw.Alignment.center,
        1: pw.Alignment.center,
        2: pw.Alignment.center,
        3: pw.Alignment.center,
        4: pw.Alignment.center,
      },
      headerStyle: pw.TextStyle(
        color: PdfColors.blueGrey,
        fontSize: 10,
        fontWeight: pw.FontWeight.bold,
      ),
      cellStyle: const pw.TextStyle(
        color: PdfColors.black,
        fontSize: 10,
      ),
      rowDecoration: pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(
            color: PdfColors.amber,
            width: .5,
          ),
        ),
      ),
      headers: List<String>.generate(
        tableHeaders.length,
            (col) => tableHeaders[col],
      ),
      data: List<List<dynamic>>.generate(
        products.length,
            (row) => List<dynamic>.generate(
          tableHeaders.length,
              (col) => products[row].getIndex(col),
        ),
      ),
    );
  }
```

**Comment by DavBfr** [comment]
Do not use fromTextArray if you want to display anything that is not text. Use directly the pw.Table widget.

**Comment by NiroopNife** [comment]
Any example i could get as how to implement the pw.Table widget?

**Comment by NiroopNife** [comment]
As per your suggestion yes it is the right way and is working as expected but how to give decoration for each row if we need to give some padding and border for each cell? Also how to fetch the image from the database and show it in pdf?

As of now I'm doing like this and getting an error as **The argument type 'List<MemoryImage>' can't be assigned to the parameter type 'List<Widget>'**
```
 pw.Widget _contentArticleScanned(pw.Context context){
    return pw.Table(
      defaultVerticalAlignment: pw.TableCellVerticalAlignment.top,
      border: pw.TableBorder.all(color: PdfColors.black, width: 1, style: pw.BorderStyle.solid),
        children: [
      pw.TableRow(

          decoration: pw.BoxDecoration(
            border: pw.TableBorder.all(color: PdfColors.black, width: 1, style: pw.BorderStyle.solid),
            color: PdfColors.grey200
          ),
          children: [
        pw.Text('SERIAL', style: pw.TextStyle(color: PdfColors.blueGrey)),
        pw.Text('ARTICLE NUMBER', style: pw.TextStyle(color: PdfColors.blueGrey)),
        pw.Text('ADDRESSEE NAME', style: pw.TextStyle(color: PdfColors.blueGrey)),
        pw.Text('REMARK', style: pw.TextStyle(color: PdfColors.blueGrey)),
        pw.Text('SIGNATURE', style: pw.TextStyle(color: PdfColors.blueGrey))
      ]),
      pw.TableRow(
          children: [getSerialNumber(context), getArticleNumber(context), getAddressee(context), getRemark(context), getImages(context), pw.Image(im, height: 20)])
    ]);
  }


pw.Widget getImages(pw.Context context){
    return pw.Column(
      children: images.map((e) => pw.MemoryImage(base64Decode(e))).toList()
    );
  }
```
Else what would be the right approach for getting the images from the database and showing it in Pdf?

**Comment by DavBfr** [comment]
You create a function generatePdf(format) async {} with:

final pdf = pw.Document()

... fetch the assets from the database ...

add the pages with pdf.addPage() and use the assets here

return the pdf file: return pdf.save()

**Comment by NiroopNife** [comment]
I'm successfully fetching the image from the database and trying to put the image in the MemoryImage since it is coming from the database but it is failing to load the image.
```
List images = [];
var response = await Article().select().onlyDate.startsWith('10-02-2021').toMapList();   //I'm fetching data from db
for(int i=0; i< response.length; i++){
  images.add(response[i]['image']);   //saving the image object in the imagesList 
  List<int> bytes = utf8.encode(images.toString());   //converting the saved images to string and encoding it to uft8
  var dbImage = await flutterImageProvider(MemoryImage(bytes, scale: 1.0));  //trying to show the image with MemoryImage
}
```

And this is how I'm saving the Image to the DB
```
List<int> _bytes;
Future getImage() async {
    final image = await ImagePicker().getImage(source: ImageSource.camera, imageQuality: 5);
    _bytes = await image.readAsBytes();  
final addToDb = Article.withFields( _bytes).upsert();
}
```

**Comment by NiroopNife** [comment]
And getting an error as 
```
image failed to load
'package:printing/src/asset_utils.dart':
Failed assertion: line 56 pos 14: 'false'
```

**Comment by DavBfr** [comment]
Try this: `var dbImage = pw.MemoryImage(bytes);`

**Comment by NiroopNife** [comment]
Now was getting an error as 
```
Unhandled Exception: NoSuchMethodError: The method 'startDecode' was called on null.
E/flutter (28411): Receiver: null
E/flutter (28411): Tried calling: startDecode(Uint8Array)
```

**Comment by NiroopNife** [comment]
I some how successfully fetched the images from the database and tried to put in the pdf by got an error as 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.
E/flutter ( 5377): #0      MultiPage.generate.<anonymous closure> (package:pdf/src/widgets/multi_page.dart:202:11)
E/flutter ( 5377): #1      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:206:8)
E/flutter ( 5377): #2      Document.addPage (package:pdf/src/widgets/document.dart:106:10)
E/flutter ( 5377): #3      _SaveArticleToDBScreenState.writeOnPdf (package:postman/Screens/Home/ScanAndDeliver/SaveArticleToDBScreen.dart:172:9)
E/flutter ( 5377): <asynchronous suspension>
E/flutter ( 5377): #4      _SaveArticleToDBScreenState.build.<anonymous closure> (package:postman/Screens/Home/ScanAndDeliver/SaveArticleToDBScreen.dart:990:19)
E/flutter ( 5377): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 5377): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 5377): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 5377): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 5377): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 5377): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter ( 5377): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 5377): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter ( 5377): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 5377): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 5377): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 5377): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 5377): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 5377): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 5377): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5377): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5377): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 5377): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

The way I'm storing into the db is in text format for now not in blob type & adding it to db
```
    image2 = await ImagePicker.pickImage(source: ImageSource.camera, maxHeight: 100, maxWidth: 100,);
    List<int> imageBytes = image2.readAsBytesSync();
    base64Image = base64Encode(imageBytes);
```

Later in the page initialization I'm getting back the images as 
```
var response;
var anIm;
List images = [];
String dummyImage = '';
Uint8List uInt8listImage, _bytesImage;
String base64Image;

db() async {
    response = await Article().select().onlyDate.startsWith('11-02-2021').toMapList();
    for(int i=0; i< response.length; i++){
       images.add(response[i]['image']);
       dummyImage = images[i];
      uInt8listImage = Base64Decoder().convert(dummyImage);
      anIm = await flutterImageProvider(MemoryImage(uInt8listImage, scale: 1.0));
    }
}

 pw.Widget _contentArticleScanned(pw.Context context){
   return pw.Table(
     children: [
          pw.TableRow(
                          children: [getdbImages(context)])
         )];
}

  pw.Widget getdbImages(pw.Context context){
    return pw.Column(
      children: uInt8listImage.map((e) => pw.Image(anIm, height: 10)).toList()
    );
  }

```

**Comment by DavBfr** [comment]
Each time you try to do something that won't fit on one page, you will get this error. The library can't draw a part of a widget on a page and the remaining on another page.

**Comment by NiroopNife** [comment]
The thing is, I'm adding the image in  a table column which eventually I'm giving a fixed height of just 10, so my question is why is it creating that whole lot of pages when I'm having only one image in my DB?

**Comment by NiroopNife** [comment]
How to do decoration for the pw.Table as it comes in the pw.Table.fromTextArray?

**Comment by DavBfr** [comment]
Look at the code for fromTextArray, it's just a function.
