### ISSUE TITLE
Unable to add multiple images in the PDF

### ISSUE THREAD

**Issue by NiroopNife** [DavBfr/dart_pdf#550]
I'm unable to add multiple images when writing the code for creating PDF, this way I'm trying to initialize it as 
```
const imageLogo= const AssetImage('assets/images/ic_developer_log.png');
final image = await flutterImageProvider(imageLogo);

const barImg = const AssetImage('assets/images/ic_developer_log.png');
final barCodeImage = await flutterImageProvider(barImg);

```
and so getting an error as 
```
I/flutter (17540): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter (17540): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
E/jniPdfium(17540): Loaded page is null
E/PDFView (17540): load pdf error
E/PDFView (17540): java.lang.IllegalStateException: cannot load page
E/PDFView (17540): 	at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(Native Method)
E/PDFView (17540): 	at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:140)
E/PDFView (17540): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:55)
E/PDFView (17540): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
E/PDFView (17540): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/PDFView (17540): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/PDFView (17540): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PDFView (17540): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PDFView (17540): 	at java.lang.Thread.run(Thread.java:919)
W/System  (17540): A resource failed to call release. 
W/System  (17540): A resource failed to call close. 
W/System  (17540): A resource failed to call release. 
W/System  (17540): A resource failed to call close. 
```
But if i just add a single image to the PDF its sucessfully built & this is how I'm initializing the single image
```
const imageLogo= const AssetImage('assets/images/ic_developer_log.png');
final image = await flutterImageProvider(imageLogo);
```
And also if I try to add a Unit8List image to the MemoryImage it is not getting loaded in the PDF. The way I'm initializing the MemoryImage is
```
var signatureImg = MemoryImage(widget.signature);
final signatureImage = await flutterImageProvider(signatureImg);
```
And showing it in the PDF like 
```
pdf.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      header: (pw.Context context) {
          return pw.Image(signatureImage); //This is how I'm showing in the UI of PDF for all the above images too
      }
   )
)
```

Getting an error for the when declared MemoryImage as 
```
W/example.postma(17540): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
E/flutter (17540): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 928 pos 14: 'bytes != null': is not true.
E/flutter (17540): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (17540): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (17540): #2      new MemoryImage (package:flutter/src/painting/image_provider.dart:928:14)
E/flutter (17540): #3      _delState.createPdf (package:postman/Screens/Home/ScanAndDeliver/del.dart:97:24)
E/flutter (17540): #4      _delState.build.<anonymous closure> (package:postman/Screens/Home/ScanAndDeliver/del.dart:1111:19)
E/flutter (17540): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (17540): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (17540): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (17540): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (17540): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (17540): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (17540): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (17540): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (17540): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (17540): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (17540): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (17540): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (17540): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (17540): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (17540): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17540): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (17540): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (17540): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (17540): 
E/jniPdfium(17540): Loaded page is null
E/PDFView (17540): load pdf error
E/PDFView (17540): java.lang.IllegalStateException: cannot load page
E/PDFView (17540): 	at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(Native Method)
E/PDFView (17540): 	at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:140)
E/PDFView (17540): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:55)
E/PDFView (17540): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
E/PDFView (17540): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/PDFView (17540): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/PDFView (17540): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PDFView (17540): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PDFView (17540): 	at java.lang.Thread.run(Thread.java:919)

```

**Comment by DavBfr** [comment]
Can you provide more code?

**Comment by NiroopNife** [comment]
```
 writeOnPdf() async {
    const imageLogo = const AssetImage(
      'assets/images/ic_arrows.png',
    );
    final image = await flutterImageProvider(imageLogo);
    svgImage = await rootBundle.loadString('assets/images/ic_invoice.svg');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        header: (pw.Context context) {
          return pw.Row(children: [
            pw.Flexible(
              flex: 1,
              child: pw.Image(image),
            ),
            pw.Flexible(
              flex: 2,
              child: pw.Column(children: [
                pw.Text('Department of Posts'),
                pw.Text('Ministry of Communications, Government of India'),
                pw.SizedBox(height: 5),
                pw.Text('DELIVERY SLIP'),
              ]),
            ),
            pw.Flexible(flex: 1, child: pw.SvgImage(svg: svgImage))
          ]);
        },
        footer: _buildFooter,
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Divider(),
            pw.SizedBox(height: 20),
            _contentDetails(context),
            pw.SizedBox(height: 40),
            _contentArticleTable(context),
            pw.SizedBox(height: 40),
            pw.Text('Delivery Details'),
            pw.SizedBox(height: 20),
            _contentDeliveryTable(context),
            pw.SizedBox(height: 50),
            _contentSignature(context),
          ];
        },
      ),
    );
  }
```
Here I'm initializing two images, but when i initialize two images it's coming as
```
E/jniPdfium(24534): Loaded page is null
E/PDFView (24534): load pdf error
E/PDFView (24534): java.lang.IllegalStateException: cannot load page
E/PDFView (24534): 	at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(Native Method)
E/PDFView (24534): 	at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:140)
E/PDFView (24534): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:55)
E/PDFView (24534): 	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
E/PDFView (24534): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/PDFView (24534): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/PDFView (24534): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PDFView (24534): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PDFView (24534): 	at java.lang.Thread.run(Thread.java:919)
```
But if in case only if i insert the Asset image rather than the Svg image then the pdf is being loaded.

Is there any way to initialize the images in the table of Pdf, even if i try to initialize an icon or an image its being displayed as in text format

**Comment by DavBfr** [comment]
Where is the pdf variable coming from? You should create the pdf object each time you want to generate a document, it's not reusable.

**Comment by NiroopNife** [comment]
I tried by initializing the image in the init state itself now getting the image in the pdf

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
