### ISSUE TITLE
How to load image from ASSETS?

### ISSUE THREAD

**Issue by chirag-chopra** [DavBfr/dart_pdf#562]
I read documentation but still not able to find out how to load image from assets..
I even tried below code:

```
pw.Image(
    image: AssetImage(
     'lib/assets/male-avatar.png'
     ),
     height: 100,
)
```

still not working...
image argument not found

PLEASE...!

**Comment by DavBfr** [comment]
Try with:

```dart
final image = MemoryImage(await rootBundle.load('lib/assets/male-avatar.png'));
pw.Image(image: image)
```

**Comment by chirag-chopra** [comment]
> Try with:
> 
> ```dart
> final image = MemoryImage((await rootBundle.load('lib/assets/male-avatar.png')).buffer.asUint8List());
> pw.Image(image: image)
> ```

No, this is not working at all
and throwing this error

```
E/flutter (23451): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'ImageProvider'
E/flutter (23451): #0      _PdfReportScreenState.generatePdf.<anonymous closure>
package:astroself/screens/pdfReportScreen.dart:64
E/flutter (23451): #1      Page.postProcess
package:pdf/…/widgets/page.dart:140
E/flutter (23451): #2      Document.save
package:pdf/…/widgets/document.dart:118
E/flutter (23451): #3      _PdfReportScreenState.savePdf
package:astroself/screens/pdfReportScreen.dart:127
E/flutter (23451): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (23451): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (23451): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (23451): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (23451): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (23451): #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (23451): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (23451): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (23451): #12     getExternalStorageDirectory (package:path_provider/path_provider.dart)
package:path_provider/path_provider.dart:1
E/flutter (23451): #13     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (23451): #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (23451): #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (23451): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (23451): #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (23451): #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (23451): #19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (23451): #20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (23451): #21     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
package:flutter/…/services/platform_channel.dart:1
E/flutter (23451): #22     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (23451): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (23451): #24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (23451): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (23451): #26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (23451): #27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (23451): #28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (23451): #29     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (23451): #30     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (23451): #31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (23451): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (23451): #33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (23451): #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by rithviknishad** [comment]
This was my solution for loading image from assets:

```dart
static Future<Image> getLogoAsImage() async {
  final data = await rootBundle.load('assets/logo_no_padding.png');

  final bytes =
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

  return Image(MemoryImage(bytes));
}
```

and consume it before performing `pdf.addPage` (since I couldn't come up with a solution to consume it during rendering as it's a future):

```dart
final _logo = await getLogoAsImage();

pdf.addPage(
  MultiPage(
    header: (context) => buildHeader(context, _logo),
    ...
  ),
);  
```
