### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by joeblew99** [DavBfr/dart_pdf#58]
env
- Android nexus 5x
- Flutter beta

It does NO crash, but it has a bit of a hickup here.
to reproduce:
got to Print Document, and then hit back, and then Print Screenshot ( and it does nothing).
I also get this on IOS Simulator.
So its more int eh dart code than the Plugin i suspect.

Output.
````
I/flutter (31147): Print Screen 376x620 ...
I/flutter (31147): Print Screen 376x620 ...
I/flutter (31147): Share ...
I/flutter (31147): Print Screen 376x620 ...
I/flutter (31147): Print ...
E/flutter (31147): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2769 pos 12: '!debugNeedsPaint': is not true.
E/flutter (31147): #0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
E/flutter (31147): #1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
E/flutter (31147): #2      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2769:12)
E/flutter (31147): #3      MyAppState._printScreen (package:print_protobuf/app.dart:53:40)
E/flutter (31147): <asynchronous suspension>
E/flutter (31147): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (31147): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (31147): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter (31147): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
E/flutter (31147): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (31147): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter (31147): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (31147): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (31147): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (31147): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (31147): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (31147): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (31147): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (31147): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (31147): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31147): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (31147): #20     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (31147): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (31147): 
E/flutter (31147): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2769 pos 12: '!debugNeedsPaint': is not true.
E/flutter (31147): #0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
E/flutter (31147): #1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
E/flutter (31147): #2      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2769:12)
E/flutter (31147): #3      MyAppState._printScreen (package:print_protobuf/app.dart:53:40)
E/flutter (31147): <asynchronous suspension>
E/flutter (31147): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (31147): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (31147): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter (31147): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
E/flutter (31147): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (31147): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter (31147): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (31147): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (31147): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (31147): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (31147): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (31147): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (31147): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (31147): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (31147): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31147): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (31147): #20     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (31147): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (31147): 
I/flutter (31147): Print Screen 376x620 ...
`````

**Comment by DavBfr** [comment]
It looks like a bug in flutter, not in this plugin.

**Comment by joeblew99** [comment]
ok lets close it for now.
