### ISSUE TITLE
Contains invalid characters

### ISSUE THREAD

**Issue by mzl1988** [DavBfr/dart_pdf#790]
lang zh-HK non-work
```
Cannot decode the string to Latin1.
This font does not support Unicode characters.
If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
---------------------------------------------
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "總分"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:89:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      PdfFont.stringMetrics (package:pdf/src/pdf/font.dart:171:28)
#3      RichText.layout.<anonymous closure> (package:pdf/src/widgets/text.dart:697:34)
#4      TextSpan.visitChildren (package:pdf/src/widgets/text.dart:463:19)
#5      RichText.layout (package:pdf/src/widgets/text.dart:666:10)
#6      Align.layout (package:pdf/src/widgets/basic.dart:309:14)
#7      MultiPage.generate (package:pdf/src/widgets/multi_page.dart:296:13)
#8      Document.addPage (package:pdf/src/widgets/document.dart:113:10)
#9      generateTrackerChartPdfFile (package:app_code/commons/document.dart:125:7)
#10     _SCCAIChartPanelState._share (package:app_code/pages/home_page/sccai_chart_panel.dart:337:24)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#23     _rootRunUnary (dart:async/zone.dart:1370:13)
#24     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#26     _invoke1 (dart:ui/hooks.dart:182:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
```

**Comment by DavBfr** [comment]
Please use a TrueType font as described here: https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by oengmengthong** [comment]
khmer font unsupport with enlish font 
![image](https://user-images.githubusercontent.com/40915642/132800791-27d1ff84-cd28-4fe5-b285-3ca678e3d2f1.png)

**Comment by DavBfr** [comment]
Is this font able to print Latin characters?
