### ISSUE TITLE
Printing 5.7.1 issues

### ISSUE THREAD

**Issue by deepak786** [DavBfr/dart_pdf#929]
By using the updated version `printing: 5.7.1`, we have the below issues:

<details>
<summary>1. Exception</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
_PdfPreviewState.dispose failed to call super.dispose.

dispose() implementations must always call their superclass dispose() method, to ensure that all the resources used by the widget are fully released.
When the exception was thrown, this was the stack: 
#0      StatefulElement.unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:4822:7)
#1      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4829:6)
#2      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#3      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#4      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#16     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6225:16)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#28     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6225:16)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#70     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6225:16)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#97     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6225:16)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#103    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#109    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#115    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#127    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#130    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#136    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#154    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#157    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#160    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#165    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#166    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#169    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#172    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#173    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#174    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#175    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)
#176    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#177    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#178    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#179    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#180    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#181    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#182    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#183    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#184    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
#185    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#186    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#187    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#188    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2837:27)
#189    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2468:15)
#190    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2836:7)
#191    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#192    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#193    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#194    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#195    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#199    _invoke (dart:ui/hooks.dart:150:10)
#200    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#201    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
====================================================================================================
```

This exception occurs when we go back from the PdfPreview page.

Platforms: Android, iOS, and Web.
</details>

<details>
<summary>2. PdfPreview on the web deletes the first character from various places.</summary>

**Screenshots:**

<img width="1106" alt="Screen Shot 2022-01-31 at 2 19 07 PM" src="https://user-images.githubusercontent.com/14223997/151764006-657e586d-f69d-4b73-bfd5-56579217590d.png">
<img width="1106" alt="Screen Shot 2022-01-31 at 2 18 58 PM" src="https://user-images.githubusercontent.com/14223997/151764018-44f516b1-ea43-45d8-8ab0-7ed60dae7ea5.png">

**Screenshots with `printing: 5.6.6`** 

<img width="1106" alt="Screen Shot 2022-01-31 at 2 19 07 PM" src="https://user-images.githubusercontent.com/14223997/151708960-09bf7abf-12fe-4566-962b-81fa9b99d3aa.png">
<img width="1106" alt="Screen Shot 2022-01-31 at 2 18 58 PM" src="https://user-images.githubusercontent.com/14223997/151708972-0e747b4f-161a-4a01-94da-c26a3003aad6.png">

</details>

**Comment by DavBfr** [comment]
Do you have an example code that reproduces it?

**Comment by deepak786** [comment]
here is the sample that produces the first exception https://github.com/deepak786/issue_pdf_929
I will update the sample for the second issue later.

**Comment by hasimsait** [comment]
I'm facing the same issues whenever pub get gets pdf ^3.7.0. Printing 5.6.6 works fine when it uses pdf 3.6.5, but 5.7.1 requires 3.7. I'm using the invoice example.

**Comment by regalmojo** [comment]
I'm facing the same issue

**Comment by DavBfr** [comment]
All should be fixed in the master branch. Please test

**Comment by deepak786** [comment]
Yes, the issues are fixed in master.
